using dotnetConf2024.Shared.Models;

namespace dotnetConf2024.Shared.Services
{
    public class SpeakerService
    {
        public IEnumerable<SpeakerModel> GetSpeakers()
        {
            var speakers = new List<SpeakerModel> {
                new SpeakerModel {
                    Id = "WillHuang",
                    Name = "Will Huang",
                    JobTitle = "多奇數位創意 技術總監",
                    PictureUrl ="./img/speakers/Will 保哥.jpg",
                    BlogUrl = "http://blog.miniasp.com/",
                    FacebookUrl = "https://www.facebook.com/will.fans/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任「多奇數位創意有限公司」技術總監。2018 年榮獲 Angular 方向的 Google Developer Expert (GDE) 開發專家。連續 16 度當選微軟最有價值專家(MVP)。2019 獲選微軟技術社群區域總監 (Microsoft Regional Director)。熟悉 Angular、JavaScript、.NET、C#、ASP.NET MVC、Go、Docker、Kubernetes 相關技術。擅長 DevOps 與組織文化建立、軟體團隊建構與管理。熱愛分享知識。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "DavidTung",
                    Name = "David Tung",
                    JobTitle = "光岩資訊資深技術顧問",
                    PictureUrl ="./img/speakers/David Tung.jpg",
                    BlogUrl = "http://studyhost.blogspot.tw/",
                    FacebookUrl = "http://www.facebook.com/DotNetWalker/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "光岩資訊資深技術顧問、歷屆微軟 TechDays、TechED 研討會講師、連續 14 年榮獲微軟最有價值專家 (MVP)、LINE API Expert(LAE)，專長領域跨及.NET開發技術、Azure DevOps、AI、ChatBot...熟悉 BPM、APS、ERP…等企業應用資訊系統之建置與導入。David 是敏捷開發與 DevOps 的熱愛者，打從 Apple II 時代開始闖蕩江湖至今，在資訊業各領域均有參與。做過 MIS/IT、當過 RD、帶過專案、團隊、也賣過軟體，寫過（這年頭已經消失了的）雜誌專欄、長年擔任企業訓練講師與顧問，出過一堆書……打從沒有物件導向，沒什麼所謂軟體生命週期管理的年代，一路經歷了無數個壯觀的大小瀑布與千瘡百孔的雷與坑、一直到今天，依舊還是一個喜歡寫 Code 的人...",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "EdwardKuo",
                    Name = "Edward Kuo",
                    JobTitle = "Microsoft Regional Director",
                    PictureUrl ="./img/speakers/Edward Kuo.jpg",
                    BlogUrl = "https://profile.edwardkuo.dev/",
                    FacebookUrl = "https://www.facebook.com/groups/286316594814216/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "用不同觀點看待軟體開發流程，具有超過十年以上開發者經驗與技術。熱愛技術也喜愛探索商業需求，在需求與技術槓桿中選擇合適的解決方案。專注於雲端架構設計與開發、供應鏈系統設計、ML/ AI、資訊安全和DevOps解決方案，擔任DevOps相關研討會、企業 DevOps 講師以及微軟技術研討會之講師",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "AndrewWu",
                    Name = "Andrew Wu",
                    JobTitle = "91APP 首席架構師",
                    PictureUrl ="./img/speakers/Andrew Wu-4.jpg",
                    BlogUrl = "https://columns.chicken-house.net/",
                    FacebookUrl = "https://www.facebook.com/andrew.blog.0928/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任職於大型軟體開發團隊的架構師，負責核心產品的服務化，與內部產品開發團隊的架構改善等任務。在過去的 20 年工作經驗，主要都專注於 Microsoft .NET Framework 開發 SaaS , B2B2C 的雲端服務。我專長的領域包括: 軟體工程，物件導向設計，分散式系統架構設計，平行處理，API 設計 及 微服務導向架構設計 (microservices) 等。<br /><br />我樂於分享技術新知與開發的經驗，常在各大研討會或是在社群活動上分享經驗。同時我也有撰寫部落格文章的習慣，希望能累積我的經驗給需要的夥伴們。我深信知識是越分享越精進的，這也是支持我自 2004 至今連續 20 年不間段分享文章的動力來源。<br /><br />個人經歷:<br />- 現任 91APP, 首席架構師 Chief Architect<br />- 榮獲 Microsoft MVP 微軟最有價值專家 獎項,2016 ~ 2025<br />- 擔任多次 Microsoft Azure Cafe, TechDays, TechEd, DevOpsDays Taiwan, .NET Conf 等大型研討會講者，與相關 Azure PaaS 雲端系列課程與企業內訓講師<br /><br />https://columns.chicken-house.net/about/",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "YinSangzhi",
                    Name = "尹相志",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/尹相志-AI.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "於 2002 年台灣創立 asiaMiner 為台灣第一家專業大數據顧問公司。2015 年正式擔任中國第一家大數據顧問公司華院數據的首席數據科學家，並於 2016 年發起中國首次人工智能大賽 BOT (Brain of things) 2016，目前於大陸成立 Deepbelief.ai 聚焦於機器視覺的創新商業應用。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "IanChan",
                    Name = "Ian Chan",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Ian.jpg",
                    BlogUrl = "https://medium.com/playtech",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/codeian/",
                    Introduction = "陳葵懋（Ian Chen），連續12年當選微軟最有價值專家(MVP/現為AI領域)，同時也是連續5年微軟認證講師（MCT）。<br/>目前任職於「一等一科技股份有限公司」，熟悉 .NET 開發、Azure 雲端，近年來專注於Azure Devops、K8s、OpenAI等技術<br/>，相信持續學習與分享能成長與收獲的更多，曾擔任微軟 TechDays、Devdays Asia 、Mopcon、Modern Web Conference等研討會講師。<br/>2024年策畫與共同著作第一本講述Azure OpenAI 的技術書籍：駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 （使用 .NET 與 Node.js）。。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KoKo",
                    Name = "KO KO",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KO KO.jpg",
                    BlogUrl = "",
                    FacebookUrl = "https://www.facebook.com/magic.panda.engineer/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Ko Ko 是一位資深的軟體工程師，也連續四年獲得微軟 AI 領域的最有價值專家（Microsoft AI MVP）獎項。他擔任許多技術年會的講者，包含了 COSCUP、ModernWeb、名古屋開源年會、香港開源年會、PyCon APAC、PyCon HK、DevDays Asia 等等的大型年會，累計已超過萬名聽眾。共同著作有《駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 (使用. NET 與 Node. Js)》一書，拿過天瓏書局暢銷排行榜第二名。經營臉書粉專「大魔術熊貓工程師」。Ko Ko 所撰寫系列文章「一起學習 Azure Machine Learning」是繁體中文圈關於 Azure Machine Learning 最完整的學習資源之一。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JiaSin",
                    Name = "陳佳新（奇步老爹）",
                    JobTitle = "奇步應用有限公司 執行長",
                    PictureUrl ="./img/speakers/陳佳新.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "具備 LINE API Expert 及 Microsoft AI MVP 專家資格，推廣 Chatbot 聊天機器人及 AI 人工智慧技術落地不遺餘力，目前是中部人的聊天機器人小小聚、彰化 AMA 小聚、彰化 Google 技術開發者社團的活動主辦人，致力於提升故鄉彰化乃至中部地區的數位化能力，同時也是「彰化旅行+」的核心成員，來彰化吃喝玩樂歡迎指名！",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },

                new SpeakerModel {
                    Id = "BruceChen",
                    Name = "Bruce Chen",
                    JobTitle = "Kingston Senior Engineer",
                    PictureUrl ="./img/speakers/Bruce Chen.jpg",
                    BlogUrl = "https://blog.kkbruce.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "任職於全美前 50 大私人企業，連續 12 年榮獲微軟最有價值專家，負責大型 B2B 資料交換、Web API 架構、Docker、Kubernetes 等系統平台架構與設計。由 ASP.NET 2.0(WebForms) 進入 .NET 的世界，喜歡分享心得於 blog.kkbruce.net 部落格，瀏覽量超過七百萬。合著作品有《ASP.NET MVC4 網站開發美學》、《ASP.NET MVC 5網站開發美學》；合譯作品《Martin Fowler 的企業級軟體架構模式》。經常於社群與研討會分享 .NET 開發與容器平台經驗，對於 ASP.NET Web API 框架有深入研究，是台灣宣導 ASP.NET Web API 的先驅。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "KevinYang",
                //    Name = "Kevin Yang",
                //    JobTitle = "",
                //    PictureUrl ="./img/speakers/Kevin Yang.jpg",
                //    BlogUrl = "https://blog.kevinyang.net/",
                //    FacebookUrl = "https://www.facebook.com/CKNotepad/",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "目前擔任 Angular Taiwan、Angular Girls Taiwan 、TypeScript Taiwan 社群管理者，Angular 線上讀書會主持人。2018 年榮獲 Angular/Web GDE (Google Developer Expert) 開發專家。微軟最有價值專家 (Visual Studio and Development Technologies)。熱衷分享任何新奇的技術資訊、不務正業(跨領域)，目前已跨入的領域有會計、醫療資訊及程式開發。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "JimmyHo",
                    Name = "Jimmy Ho",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Jimmy Ho-02.jpg",
                    BlogUrl = "https://jiaming0708.github.io/",
                    FacebookUrl = "https://www.facebook.com/secretgogoworld",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個熱愛學習、分享並且近期狂點前端技能樹的小小工程師，什麼都會什麼都不奇怪。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "GelisWu",
                //    Name = "Gelis 吳俊毅",
                //    JobTitle = "資深 .NET 技術顧問 & Microsoft MVP 連續七屆",
                //    PictureUrl ="./img/speakers/Gelis Wu.jpg",
                //    BlogUrl = "http://gelis-dotnet.blogspot.com/",
                //    FacebookUrl = "https://www.facebook.com/groups/361804473860062/",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "我目前是個軟體生命週期導入專業顧問<br/>我專精於顧問與協助企業流程改造(電子化)協助將商業邏輯服務化、彈性化: 以 SOA 服務導向架構的方式提供 API 框架，讓各應用程式在開發時容易調用，加速開發、並可提高商業邏輯的再利用率，協助呈現介面多元化等。同時也擅長協助提升企業的軟體專案開發與工作效率，協助企業內部制定開發團隊流程 (Coding Rule/Standard) 與技術一致化，統一開發環境與技術、應用協同工作平台 Azure DevOps 建置雲端相關應用、自動化部署工具評估與導入。<br/>同時因為專案開發出身，我同時也擅長協助企業建置 ERP/CRM/CMS 或企業內部 EIP 等相關系統。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "BaoChengyou",
                    Name = "鮑承佑",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/鮑承佑.jpg",
                    BlogUrl = "https://linktr.ee/windperson",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "本人於 2007 年底投身資訊業，從原本寫 Java， 2009 年開始接觸 WPF、Silverligh t的 C# 桌面應用程式開始投入 .NET開發，之後於資拓宏宇擔任軟體專案工程師，於 2014 年投入遊戲業在台灣卡普空擔任開發組組長，2018 到2024 上半在XR領域相關新創擔任 CTO；Unity, Xamarin/MAUI, ASP.NET Core, Blazor, Azure SignalR 等前後端與Azure雲端開發技術都略懂略懂，但抓 bug 比較在行。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "RyanChung",
                //    Name = "Ryan Chung",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/Ryan Chung.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "Ryan Chung，行動開發學院創辦人，曾獲微軟人工智能大賽特別獎、Udacity AI 產品經理微學位。目前為美國 Pluralsight 認證講師、中央大學 AI 學程兼任講師、元智大學資工系兼任助理教授級專業技術人員。專長於 Web/App 應用開發、企業 AI 加值導入、微軟 OpenAI 與認知服務應用整合。2022 年起，獲選為微軟 MVP - AI 人工智慧最有價值專家。共同著作：駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐（使用 .NET 與 Node.js）。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "Summit",
                //    Name = "孫玉峰",
                //    JobTitle = "台灣角川 數據架構師",
                //    PictureUrl ="./img/speakers/孫玉峰.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "在多個產業開發各種資料產品，包含推薦系統以及廣告數據平台，近年來的公開演講以及實務上則專注在資料工程與 MLOps 的建立，期望讓數據驅動（Data-Driven）的觀念帶動各個產業領域的創新。<br/>在東吳及師大擔任業界講師，亦接受過各媒體專訪，目前也是微軟 AI 領域最有價值專家（MVP）以及 Taiwan R User Group（常態活動 MLDM Monday 主辦單位）的共同主持人。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "BenChen",
                //    Name = "陳奎銘",
                //    JobTitle = "Principal Data Scientist @ OneLab",
                //    PictureUrl ="./img/speakers/BenChen.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "有幸成為微軟 AI 領域 MVP 的資料科學家，致力於用資料科學解決各個領域的疑難雜症，舉凡投資、生技醫療和其他傳統產業，都有相關實務處理的經驗。除此之外，不定期也會接到授課的邀約，協助不同組織機構初探數位轉型，進入資料科學的世界。同時，我也是 R-Ladies Taipei Co-organizer，正嘗試努力每個月都舉辦活動，繼續延續社群的活力。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "AlanTsai",
                //    Name = "Alan Tsai",
                //    JobTitle = "微軟最有價值專家",
                //    PictureUrl ="./img/speakers/Alan Tsai.jpg",
                //    BlogUrl = "https://blog.alantsai.net/",
                //    FacebookUrl = "http://fb.alantsai.net/",
                //    TwitterUrl = "http://twitter.alantsai.net/",
                //    LinkedinUrl = "http://linkedin.alantsai.net/",
                //    YouTubeUrl = "http://yt.alantsai.net/",
                //    Introduction = "深耕 .NET 軟體開發多年，深信使用的技術不是重點，重點在於如何全面的思考並且用適合的技術解決客戶的問題，為現任的微軟最有價值專家（Microsoft MVP）- Azure，微軟認證講師（MCT），樂於分享，深信教就是最好的學習方式，定期發佈部落格（Alan Tsai 的學習筆記）文章、影片、演講分享或者幫忙翻譯。很宅，除了上班之外會出去應該都是參加/協助社群活動（Azure Taiwan），為現任 Study4.TW 成員之一。除了程式以外，就愛看小說。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "MarcusTung",
                    Name = "Marcus Tung",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Marcus Tung.jpg",
                    BlogUrl = "https://marcus116.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/marcus.tung.3",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家（Developer Technologies）和 DevOps Taiwan 技術社群志工，樂於研究與分享 後端技術，將學習與實踐的心得記錄在個人部落格 m@rcus 學習筆記上，並於粉絲團不定期分享技術開發與 Observability 相關新知。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Mike",
                    Name = "黃升煌 Mike",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Mike.jpg",
                    BlogUrl = "https://wellwind.idv.tw/blog/",
                    FacebookUrl = "https://www.facebook.com/fullstackledder",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前是 Microsoft MVP 及 Angular，熟悉 .NET WebAPI 與 Angular 開發技術，主要於個人部落格分享學習知識，並活躍於 Angular Taiwan Facebook 社團。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BillChung",
                    Name = "Bill Chung",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Bill Chung.jpg",
                    BlogUrl = "https://www.dotblogs.com.tw/billchung",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個單純喜歡說故事的人。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JamesTsai",
                    Name = "James Tsai",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/James Tsai.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任 Microsoft MVP - Developer Technologies (2015~) 與 骨架資訊有限公司的技術總監。從 10 年多前開始接觸 .NET 程式開發後，經歷過撰寫各家行動平台的 App 與 Azure 雲端應用服務整合。Blog: https://xamarintech.blogspot.tw 與點部落: https://dotblogs.com.tw/jamestsai，內容涵蓋 Xamarin、Azure 服務與 Microsoft 365 的 Intune 相關應用等開發紀錄。並持續經營當前台灣最活耀的 Xamarin 社群 (Facebook 社群名稱: Xamarin Asia Developers)，與專注於跨平台應用開發與 CI/CD 整合、企業行動化資料保護…等的技術的研究與推廣。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Weithenn",
                    Name = "王偉任 Weithenn",
                    JobTitle = "Micron - IT Staff Architect",
                    PictureUrl ="./img/speakers/Weithenn.jpg",
                    BlogUrl = "https://www.weithenn.org/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續十三年成功獲選 Microsoft MVP 和 VMware vExpert 技術專家，並長期擔任網管人雜誌技術專欄作家。<br />曾擔任 Kubernetes Summit 2024, Hello World Dev Conoference 2024, DevOpsDays Taipei 2024、Cloud Summit 2024、SRE Conference 2024、DevOpsDays Tokyo 2024、Google DevFest Taipei 2023、.Net Conf Taiwan 2023、Modern Web Conference 2023、Kubernetes Summit 2023、DevOpsDays Taipei 2023、COSCUP 2023、Cloud Summit Taiwan 2023……等研討會講師。<br />專長為打造 SDDC 軟體定義資料中心、HCI 超融合解決方案、IaC 基礎架構即程式碼環境……等，著有微軟 S2D 軟體定義儲存技術實戰……等共 19 本著作。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "James Fu",
                    Name = "James Fu",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/James Fu.jpg",
                    BlogUrl = "https://dotblogs.com.tw/jamesfu",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "主要專長在系統架構設計、資料庫效能調教等實作經驗。在 STUDY4.TW 社群擔任講師，推廣 SQL Server 與 Hyper-V 相關技術，具 MCSE 國際認證執照，獲選為微軟最有價值專家（MVP）。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "hwchiu",
                //    Name = "邱宏瑋",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/hwchiu.png",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "目前擔任微軟 MVP (Cloud and Datacenter Management), Cloud Native Taiwan User Group 志工; 喜愛撰寫部落格分享技術，參加鐵人賽並出版 Kubernetes 相關書籍，亦有開設 Kubernetes 線上課程並經營個人 粉絲團 定期分享 Cloud Native 相關新知",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "RobersonLiou",
                //    Name = "Roberson Liou",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/RobersonLiou.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "現任微軟最有價值專家（Developer Technologies），也是 twMVC 及 DevOps Taiwan 的社群志工。<br/>喜歡參加社群的技術交流活動，並不定期在部落格（工程良田的小球場）上記錄自己踩坑的一些心得。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "LinZhengxiang",
                //    Name = "林正祥",
                //    JobTitle = "",
                //    PictureUrl ="./img/speakers/林正祥.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "樂於研究與分享新技術，喜歡使用各項網頁技術解決各項問題。主要專研 .NET 相關 Solution 為主，以及 Angular & Vue.js 等前端技術，並在第十二屆 iT 邦幫忙鐵人賽中的 Modern Web 組獲得佳作。於 2022 年出版 ASP.NET Core 6 實戰守則：超易懂的跨平台開發入門教學，並榮登天瓏年度排行第二名",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "JimmyLiao",
                    Name = "Jimmy Liao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/JimmyLiao.jpg",
                    BlogUrl = "https://jimmyliao.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/jimmyliao/",
                    Introduction = @"Jimmy Liao 先後就職於 Appier/Microsoft/InfuseAI/IBM 。專業技能橫跨應用程式、手機應用、後端開發、廣告投放、機器學習專案開發，近期致力於 Generative AI 以及相關應用推廣，協助客戶技術落實及技術諮詢。目前為 Google 生成式 AI 開發專家 (Google Developer Expert of Generative AI)。<br />日常生活就是跑步，曾經以跑步為通勤工具之一 (單程 20+ km)。接下來目標是台北馬拉松/大阪馬拉松",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KeiLiao",
                    Name = "Kei Liao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KeiLiao.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "TBD",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                }
            };

            return speakers;
        }
    }
}
