using dotnetConf2024.Shared.Models;

namespace dotnetConf2024.Shared.Services
{
    public class SpeakerService
    {
        public IEnumerable<SpeakerModel> GetSpeakers()
        {
            var speakers = new List<SpeakerModel> {
                new SpeakerModel {
                    Id = "WillHuang",
                    Name = "Will Huang",
                    JobTitle = "多奇數位創意 技術總監",
                    PictureUrl ="./img/speakers/Will 保哥.jpg",
                    BlogUrl = "http://blog.miniasp.com/",
                    FacebookUrl = "https://www.facebook.com/will.fans/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任「多奇數位創意有限公司」技術總監。2024 年榮獲 ML/GenAI 方向的 Google Developer Expert (GDE) 開發專家。2018 年榮獲 Angular 方向的 Google Developer Expert (GDE) 開發專家。連續 16 度當選微軟最有價值專家(MVP)。2019 獲選微軟技術社群區域總監 (Microsoft Regional Director)。熟悉 Angular、JavaScript、.NET、C#、ASP.NET MVC、Go、Docker、Kubernetes 相關技術。擅長 DevOps 與組織文化建立、軟體團隊建構與管理。熱愛分享知識。",
                    Topic = "ASP.NET Core 9.0 全新功能探索",
                    TopicOutline = "全新的 .NET 9.0 帶來了更進一步的效能提升，並推出多項創新功能，為開發者提供更強大的工具和更高的開發效率。這次的 ASP.NET Core 9.0 不僅引入了針對雲端原生應用的增強支援，更整合了最新的 C# 13 語言特性，為開發者提供更多彈性與更簡潔的語法。在這個版本中，我們將見識到全新的 Native AOT 編譯優化、改進的垃圾回收機制，及更多針對高效能 Web 應用的強化功能。<br/>這場演講將帶領大家探索 ASP.NET Core 9.0 的新特性，揭示其如何為開發工作帶來革新與便利。準備好站在技術的尖端，一起深入了解這個激動人心的 ASP.NET Core 新世界吧！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "DavidTung",
                    Name = "David Tung",
                    JobTitle = "光岩資訊資深技術顧問",
                    PictureUrl ="./img/speakers/David Tung.jpg",
                    BlogUrl = "http://studyhost.blogspot.tw/",
                    FacebookUrl = "http://www.facebook.com/DotNetWalker/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "光岩資訊資深技術顧問、歷屆微軟 TechDays、TechED 研討會講師、連續 14 年榮獲微軟最有價值專家 (MVP)、LINE API Expert(LAE)，專長領域跨及.NET開發技術、Azure DevOps、AI、ChatBot...熟悉 BPM、APS、ERP…等企業應用資訊系統之建置與導入。David 是敏捷開發與 DevOps 的熱愛者，打從 Apple II 時代開始闖蕩江湖至今，在資訊業各領域均有參與。做過 MIS/IT、當過 RD、帶過專案、團隊、也賣過軟體，寫過（這年頭已經消失了的）雜誌專欄、長年擔任企業訓練講師與顧問，出過一堆書……打從沒有物件導向，沒什麼所謂軟體生命週期管理的年代，一路經歷了無數個壯觀的大小瀑布與千瘡百孔的雷與坑、一直到今天，依舊還是一個喜歡寫 Code 的人...",
                    Topic = "大型語言模型（LLM）對軟體開發的影響",
                    TopicOutline = "過去這兩年，是 AI 顛覆世界的兩年。<br/>本以為 LLM 的出現，受到衝擊的會是一般上班族的工作。沒想到，現在看起來，改變最多的也很可能是軟體開發人員。LLM出現之後，軟體開發流程、方法、甚至內容，都有著天翻地覆的改變。因著AI，我們的開發速度變快、品質變好，但需要寫的 Code 卻愈來愈少！<br/>在這個場次中，我們將和大家一起看看，如何透過LLM為軟體開發賦能，我們將一同探索，未來的軟體開發將會有哪些改變?",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "EdwardKuo",
                    Name = "Edward Kuo",
                    JobTitle = "Microsoft Regional Director",
                    PictureUrl ="./img/speakers/Edward Kuo.jpg",
                    BlogUrl = "https://profile.edwardkuo.dev/",
                    FacebookUrl = "https://www.facebook.com/groups/286316594814216/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "用不同觀點看待軟體開發流程，具有超過十年以上開發者經驗與技術。熱愛技術也喜愛探索商業需求，在需求與技術槓桿中選擇合適的解決方案。專注於雲端架構設計與開發、供應鏈系統設計、ML/ AI、資訊安全和DevOps解決方案，擔任DevOps相關研討會、企業 DevOps 講師以及微軟技術研討會之講師",
                    Topic = "利用 Azure 實現平台工程：從概念到實踐",
                    TopicOutline = "平台工程是一門專注於構建工具和工作流程的學科，改善開發人員的體驗，減少他們的認知負擔，並提高生產力。本次演講將展示如何利用Azure技術來實現這些目標。通過的工具和服務，平台工程能夠簡化開發和運維的流程。並探討將本地系統與Azure技術無縫整合，從而構建高效的混合雲平台。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "AndrewWu",
                    Name = "Andrew Wu",
                    JobTitle = "91APP 首席架構師",
                    PictureUrl ="./img/speakers/Andrew Wu-4.jpg",
                    BlogUrl = "https://columns.chicken-house.net/",
                    FacebookUrl = "https://www.facebook.com/andrew.blog.0928/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任職於大型軟體開發團隊的架構師，負責核心產品的服務化，與內部產品開發團隊的架構改善等任務。在過去的 20 年工作經驗，主要都專注於 Microsoft .NET Framework 開發 SaaS , B2B2C 的雲端服務。我專長的領域包括: 軟體工程，物件導向設計，分散式系統架構設計，平行處理，API 設計 及 微服務導向架構設計 (microservices) 等。<br/>我樂於分享技術新知與開發的經驗，常在各大研討會或是在社群活動上分享經驗。同時我也有撰寫部落格文章的習慣，希望能累積我的經驗給需要的夥伴們。我深信知識是越分享越精進的，這也是支持我自 2004 至今連續 20 年不間段分享文章的動力來源。<br/>個人經歷:<br/>- 現任 91APP, 首席架構師 Chief Architect<br/>- 榮獲 Microsoft MVP 微軟最有價值專家 獎項,2016 ~ 2025<br/>- 擔任多次 Microsoft Azure Cafe, TechDays, TechEd, DevOpsDays Taiwan, .NET Conf 等大型研討會講者，與相關 Azure PaaS 雲端系列課程與企業內訓講師<br/>https://columns.chicken-house.net/about/",
                    Topic = ".NET RAG 神器 - Microsoft Kernel Memory 的應用",
                    TopicOutline = "RAG 是其中一個案例，搞懂它後我才體會到，RAG 不是個\"技術\"，它更像是個 Design Pattern，一個讓 LLM 能根據事實回答問題的設計模式。<br/>今天，我想談這兩個主軸:<br/>1. 如何在你的應用程式中善用 prompt 來解決問題？<br/>在\"軟體\"內使用的 prompt, 是 developer 該掌握的，這是 RAG 的基礎，這是今天的主軸之一<br/>2. 資料的檢索跟應用<br/>這部分有很多固定的模式了，包含文件的擷取、分段、向量化等等。是否有服務將這些都封裝妥當，只要呼叫 API 就能使用？這就是我想介紹的 Kernel-Memory，來自 Microsoft 的 Open Source Project，第二個想談的主題<br/>當你搞懂 RAG 是怎麼一回事，而也有 Kernel-Memory 這樣的服務為基礎，那你可以嘗試用 NO CODE 的平台了。在 NO CODE 平台上串接 API 來達成 RAG 的效果則是絕配。最後我會用 Dify 來示範，當作這個 session 的總結。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "YinSangzhi",
                    Name = "尹相志",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/尹相志-AI.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "DataDecision.ai數據科學家，大數據行業經歷今年第25年，於2002年成立台灣第一家大數據顧問公司asiaMiner，曾經協助台灣大大型電信公司（中華電信、遠傳電信、台灣大哥大）、銀行（中國信託、台新、台灣銀行、元大、新光、萬泰...等、零售業（特力屋、屈臣氏，7-11）...等企業導入數據科學相關產業應用。也是臺灣微軟在數據科學領域的特約講師，曾獲選2006~2017年微軟最有價值專家(MVP)，於2015~2016年曾兼任上海華院數據（中國第一家大數據顧問公司）之首席數據科學家，於任內發起中國首次國際人工智能競賽「BOT (Brain of things) Shanghai 2016」，同時也擔任2016年與2017年的賽題設計。現任中興保全科技、光寶科技、啟雲科技之企業顧問",
                    Topic = "Paradoxism：將偽代碼 prompt 變身為適合用於自動化的真代碼",
                    TopicOutline = "這陣子我一直在推廣名為偽代碼prompt：他用機器語言（程式）來描述流程，而用人類的自然語言來描述執行細節，雖然效果好的出奇，但是生成式AI的不確定性就成為自動化時的最大陰影。Paradoxism是我在這主題上的最新嘗試，如何將偽代碼以優雅的形式轉換成真代碼之外，同時也能持續優雅的處理輸出格式檢查，並且能自動將任務並行化的同時，還能個別錯誤重執行，課程中將除了這些技術部分，還同時會分享AI工作流自動化的一些心得以及技術決策的考量",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "IanChan",
                    Name = "Ian Chan",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Ian.jpg",
                    BlogUrl = "https://medium.com/playtech",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/codeian/",
                    Introduction = "陳葵懋（Ian Chen），連續12年當選微軟最有價值專家(MVP/現為AI領域)，同時也是連續5年微軟認證講師（MCT）。<br/>目前任職於「一等一科技股份有限公司」，熟悉 .NET 開發、Azure 雲端，近年來專注於Azure Devops、K8s、OpenAI等技術<br/>，相信持續學習與分享能成長與收獲的更多，曾擔任微軟 TechDays、Devdays Asia 、Mopcon、Modern Web Conference等研討會講師。<br/>2024年策畫與共同著作第一本講述Azure OpenAI 的技術書籍：駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 （使用 .NET 與 Node.js）。。",
                    Topic = "解密 AI Agent 開發：用 .NET 驅動下一代生成式應用",
                    TopicOutline = "在本次演講中，我將深入解說探索如何利用 .NET 技術開發高效的 AI Agent，驅動下一代生成式應用。透過整合 Azure AI Studio 與各大主流模型，如 Meta Llama、OpenAI GPT、Phi3 及 Hugging Face 的開源模型，展示如何在一個平台上實現多種模型連接，擴展 AI 的應用場景與功能。<br/>同時，我也將展示使用開源的 Semantic Kernel 框架，如何快速打造生成式 AI Agent 應用，讓.NET 開發者能夠輕鬆實現AI代理人的應用，無需從零開始。<br/>除此之外，我會進行 AI Agent 的功能性解說，深入探討其技術架構與運行方式，讓與會者對 AI Agent 的開發與應用有更深層次的了解。<br/>無論你是想提升生成式 AI 的開發效率，還是想探索不同模型間的整合應用，本次演講內容將為你提供豐富的實作指南。一起解密如何用 .NET 驅動下一代生成式 AI 應用！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KoKo",
                    Name = "KO KO",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KO KO.jpg",
                    BlogUrl = "",
                    FacebookUrl = "https://www.facebook.com/magic.panda.engineer/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Ko Ko 是一位資深的軟體工程師，也連續四年獲得微軟 AI 領域的最有價值專家（Microsoft AI MVP）獎項。他擔任許多技術年會的講者，包含了 COSCUP、ModernWeb、名古屋開源年會、香港開源年會、PyCon APAC、PyCon HK、DevDays Asia 等等的大型年會，累計已超過萬名聽眾。共同著作有《駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 (使用. NET 與 Node. Js)》一書，拿過天瓏書局暢銷排行榜第二名。經營臉書粉專「大魔術熊貓工程師」。Ko Ko 所撰寫系列文章「一起學習 Azure Machine Learning」是繁體中文圈關於 Azure Machine Learning 最完整的學習資源之一。",
                    Topic = "從 MLOps 到 LLMOps 的典範轉移",
                    TopicOutline = "在這場演講中，將帶大家了解從 MLOps 到 LLMOps 的根本性變革。這場典範轉移意指 MLOps 在應對大語言模型的不確定性和複雜管理需求時，舊有的觀念已無法滿足新型態應用的需求。透過分析 MLOps 與 LLMOps 的核心差異，我們可以看到這一轉變如何改變機器學習產品的開發、管理和維運的方式。<br/>本次演講同時會深入分析 LLM 在應用場景中的挑戰，尤其是其動態的資料需求和風險控制需求。LLMOps 不僅涉及回答品質的監控和偏見檢測，還需持續收集用戶反饋並進行 Prompt 與資料的優化，以應對商業場景更新頻繁、迭代速度快的需求。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JiaSin",
                    Name = "陳佳新（奇步老爹）",
                    JobTitle = "奇步應用有限公司 執行長",
                    PictureUrl ="./img/speakers/陳佳新.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "具備 LINE API Expert 及 Microsoft AI MVP 專家資格，推廣 Chatbot 聊天機器人及 AI 人工智慧技術落地不遺餘力，目前是中部人的聊天機器人小小聚、彰化 AMA 小聚、彰化 Google 技術開發者社團的活動主辦人，致力於提升故鄉彰化乃至中部地區的數位化能力，同時也是「彰化旅行+」的核心成員，來彰化吃喝玩樂歡迎指名！",
                    Topic = "用 AI Agent 分析萬人活動及校正異常",
                    TopicOutline = "在 LLM 大語言模型的時代，打造各種專屬功能的 AI Agent 成了開發者的日常，因應各行各業都遭遇的缺工問題， AI Agent 已經開始扮演起重要的智囊團角色，舉凡分析數據、提供建議，都可以借重 AI Agent 之力，所花費的時間甚至更少，所獲得成效甚至更棒。本議程將以我們在彰化舉辦的萬人參加的活動為例，說明 AI Agent 如何協助分析，提供決策參考，並且盡可能降低民眾人為因素所導致的異常，大幅提升活動的公平性。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },

                new SpeakerModel {
                    Id = "BruceChen",
                    Name = "陳傳興（Bruce Chen）",
                    JobTitle = "Kingston Senior Engineer",
                    PictureUrl ="./img/speakers/Bruce Chen.jpg",
                    BlogUrl = "https://blog.kkbruce.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "由MS-DOS 6.22與Intel 486 DX2-66進入資訊領域，在QBasic寫下第一行Hello World，就愛上了開發的世界，目前任職於遠東金士頓科技擔任資深工程師。現任微軟最有價值專家（Microsoft MVP），喜歡分享技術心得於部落格（https://blog.kkbruce.net），瀏覽量超過七百萬。經常出沒於STUDY4與twMVC社群與其他研討會。合著出版作品有《ASP.NET MVC 4網站開發美學》、《ASP.NET MVC 5網站開發美學》。合譯出版作品有《Martin Fowler的企業級軟體架構模式》。審校出版作品有《重構：改善 .NET 與 C# 應用程式的設計，償還欠下的技術債》、《無瑕的程式碼 軟體工匠篇：程式設計師必須做到的紀律、標準與倫理》，協助翻譯GitHub上擁有18.5K星星的《ASP.NET Core開發人員指南》，為繁體與簡體中文化的主要貢獻者。",
                    Topic = "以審校的角度看 Uncle Bob《無瑕的程式碼 軟體工匠篇》烏托邦",
                    TopicOutline = "很高興有機會審校Uncle Bob的《無瑕的程式碼 軟體工匠篇》一書，書中針對軟體工程師提出三件非常重要的事：「紀律、標準與倫理」。它為軟體工程師們提供了一個非常好的指導原則（GuideLine）。在審校過程每次重讀（初校、一校、二校、三校…）都有不同的心得與感想，因此，想要借此機會來與大家一起聊聊Uncle Bob的軟體匠人烏托邦與審校心裡的軟體匠人桃花源。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "KevinYang",
                //    Name = "Kevin Yang",
                //    JobTitle = "",
                //    PictureUrl ="./img/speakers/Kevin Yang.jpg",
                //    BlogUrl = "https://blog.kevinyang.net/",
                //    FacebookUrl = "https://www.facebook.com/CKNotepad/",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "目前擔任 Angular Taiwan、Angular Girls Taiwan 、TypeScript Taiwan 社群管理者，Angular 線上讀書會主持人。2018 年榮獲 Angular/Web GDE (Google Developer Expert) 開發專家。微軟最有價值專家 (Visual Studio and Development Technologies)。熱衷分享任何新奇的技術資訊、不務正業(跨領域)，目前已跨入的領域有會計、醫療資訊及程式開發。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "JimmyHo",
                    Name = "Jimmy Ho",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Jimmy Ho-02.jpg",
                    BlogUrl = "https://jiaming0708.github.io/",
                    FacebookUrl = "https://www.facebook.com/secretgogoworld",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "我是 Jimmy ，在開發技術上從前端到後端 Dotnet，甚至 Cordova/Flutter 手機的應用也都碰，更不用說維運這方面的應用，什麼都碰什麼都學，喜歡學習、分享的一條龍工程師。",
                    Topic = "系統上線後的問題排查，反思系統設計",
                    TopicOutline = "系統上線以後收到問題的回報，才會發現當初的一些設計是否不足或是過度，這次就實務上所遇到的案例來做探討反思，例如 log 追蹤困難、效能問題、API schema 設計。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "GelisWu",
                //    Name = "Gelis 吳俊毅",
                //    JobTitle = "資深 .NET 技術顧問 & Microsoft MVP 連續七屆",
                //    PictureUrl ="./img/speakers/Gelis Wu.jpg",
                //    BlogUrl = "http://gelis-dotnet.blogspot.com/",
                //    FacebookUrl = "https://www.facebook.com/groups/361804473860062/",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "我目前是個軟體生命週期導入專業顧問<br/>我專精於顧問與協助企業流程改造(電子化)協助將商業邏輯服務化、彈性化: 以 SOA 服務導向架構的方式提供 API 框架，讓各應用程式在開發時容易調用，加速開發、並可提高商業邏輯的再利用率，協助呈現介面多元化等。同時也擅長協助提升企業的軟體專案開發與工作效率，協助企業內部制定開發團隊流程 (Coding Rule/Standard) 與技術一致化，統一開發環境與技術、應用協同工作平台 Azure DevOps 建置雲端相關應用、自動化部署工具評估與導入。<br/>同時因為專案開發出身，我同時也擅長協助企業建置 ERP/CRM/CMS 或企業內部 EIP 等相關系統。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "BaoChengyou",
                    Name = "鮑承佑",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/鮑承佑.jpg",
                    BlogUrl = "https://linktr.ee/windperson",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "本人於 2007 年底投身資訊業，從原本寫 Java，2009 年開始接觸 WPF、Silverlight 的 C# 桌面應用程式開始投入 .NET 開發，之後於資拓宏宇擔任軟體專案工程師，於 2014 年投入遊戲業在台灣卡普空擔任開發組組長，2018 到 2023 上半在 XR 領域相關新創擔任 CTO<br/>Unity、Xamarin/MAUI、ASP.NET Core、Blazor、Azure SignalR 等前後端與 Azure 雲端開發技術都略懂略懂，但抓 bug比較在行。",
                    Topic = "PowerShell TDD 起步走",
                    TopicOutline = "介紹如何入門 PowerShell 的 TDD （Test-Driven Development 測試驅動開發）：<br/>◦ 如何用 Visual Studio Code 建置 PowerShell TDD開發環境<br/>◦ PowerShell 測試工具框架 Pester介紹、為既有 PowerShell script加上可執行的測試案例<br/>◦ PowerShell + C# binary cmdlet、ASP.NET Core 整合 PowerShell Hosting Script 的 TDD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "RyanChung",
                //    Name = "Ryan Chung",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/Ryan Chung.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "Ryan Chung，行動開發學院創辦人，曾獲微軟人工智能大賽特別獎、Udacity AI 產品經理微學位。目前為美國 Pluralsight 認證講師、中央大學 AI 學程兼任講師、元智大學資工系兼任助理教授級專業技術人員。專長於 Web/App 應用開發、企業 AI 加值導入、微軟 OpenAI 與認知服務應用整合。2022 年起，獲選為微軟 MVP - AI 人工智慧最有價值專家。共同著作：駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐（使用 .NET 與 Node.js）。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "Summit",
                    Name = "孫玉峰",
                    JobTitle = "台灣角川 數據架構師",
                    PictureUrl ="./img/speakers/孫玉峰.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "在多個產業開發各種資料產品，包含推薦系統以及廣告數據平台，近年來的公開演講以及實務上則專注在資料工程與 MLOps 的建立，以數據驅動（Data-Driven）的觀念帶動各個產業領域的創新。<br/>曾在東吳及師大擔任業界講師，亦接受過各媒體專訪，目前也是微軟 AI 領域最有價值專家（MVP）以及 Taiwan R User Group（常態活動 MLDM Monday 主辦單位）的共同主持人。",
                    Topic = "《不時輕聲地以幻覺遮羞的大型語言模型｜來幫你的 LLMOps 做個健康檢查吧》",
                    TopicOutline = "你開始使用大型語言模型（LLMs）了嗎？你有遇到導入 LLMs 之後的部署及維運問題嗎？去年我們說身為開發者無可避免要處理 LLMOps（Large Language Model Operations）的議題，你踩到多少個坑了呢？（欸<br/>LLMs 讓我們能夠開發許多以前無法做到的功能，但身為一個機率模型，常常出現幻覺也是很合理的。本次分享將從 LLMs 的本質與特性談起，聊聊在開發 LLMOps 的過程中，如何適時進行健康檢查，讓 LLMs 能真正為你的產品／應用加分",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "BenChen",
                   Name = "陳奎銘",
                   JobTitle = "Principal Data Scientist @ OneLab",
                   PictureUrl ="./img/speakers/BenChen.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "有幸成為微軟 AI 領域 MVP 的資料科學家，致力於用資料科學解決各個領域的疑難雜症，舉凡投資、生技醫療和其他傳統產業，都有相關實務處理的經驗。除此之外，不定期也會接到授課的邀約，協助不同組織機構初探數位轉型，進入資料科學的世界。同時，我也是 R-Ladies Taipei Co-organizer，正嘗試努力每個月都舉辦活動，繼續延續社群的活力。",
                   Topic = "投資書僮進化中～GraphRAG！",
                   TopicOutline = "去年，我和我的投資書僮一起用 RAG 在股海中冒險，我們一起讀財報、找標的、做分析...<br/>雖然～我們賺到了一些～但是！還是踩到雷了！財報果然還是會隱惡揚善～<br/>看來，財報上的隱藏風險，靠 RAG 似乎沒辦法看清全貌<br/>為了不再當財報美化的受害者，只好想辦法進化了～～用 GraphRAG 從全局視角找出種種疑點...<br/>這次分享將會聚焦在 GraphRAG 的介紹與應用，以及各種實務作法與注意事項～",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                   SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                   IsShow = true,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "AlanTsai",
                   Name = "Alan Tsai",
                   JobTitle = "微軟最有價值專家",
                   PictureUrl ="./img/speakers/Alan Tsai.jpg",
                   BlogUrl = "https://blog.alantsai.net/",
                   FacebookUrl = "http://fb.alantsai.net/",
                   TwitterUrl = "http://twitter.alantsai.net/",
                   LinkedinUrl = "http://linkedin.alantsai.net/",
                   YouTubeUrl = "http://yt.alantsai.net/",
                   Introduction = "熱愛學習、分享與教學，專精於 .NET (Core)、ASP.NET Core、Azure、架構設計、Container、DevOps、Bot Framework (chatbot), ==GitHub Copilot== 等領域。<br/>堅信教學是最佳的學習方式，喜歡將新知轉化為文章、影片、課程與演講，並在「Alan Tsai 的學習筆記」部落格分享。<br/>同時，也熱衷於翻譯軟體/文章，目前已翻譯了兩本書。<br/>榮幸擔任微軟最有價值專家 (MVP) - Azure和微軟認證講師 (MCT)，並擁有數十張與Azure相關的證照。<br/>除了工作之外，我也非常喜歡參與和協助社群活動，是Study4.TW的成員之一。閒暇時，我喜歡閱讀小說和打打手遊。<br/>如果有機會參加活動，歡迎找我聊聊哦！<br/>期待與大家建立聯繫，一同學習和成長！",
                   Topic = "初探 Drasi：微軟開源的 Data Change Processing Platform",
                   TopicOutline = "在現代化的系統架構中，微服務化（Microservices）已成為趨勢。<br/>然而，隨之而來的一個常見問題就是：資料共享該如何處理？<br/>過去，當所有系統都集中在同一個地方時，直接存取資料是理所當然的選擇。但在微服務架構中，我們是否還應該這樣做？如果不應該，那有哪些建議的做法？<br/>Drasi 的誕生正是為了解決這些挑戰。<br/>讓我們一起探索 Drasi，了解何為一個資料變更處理平台，以及帶來什麼好處。",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                   SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                   IsShow = true,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "MarcusTung",
                    Name = "Marcus Tung",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Marcus Tung.jpg",
                    BlogUrl = "https://marcus116.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/marcustung.tech",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家（Developer Technologies）和 DevOps Taiwan 技術社群志工，樂於研究與分享 後端技術，將學習與實踐的心得記錄在個人部落格 m@rcus 學習筆記上，並於粉絲團不定期分享技術開發與 Observability 相關新知。",
                    Topic = ".NET x Keycloak：從 0 到 1 建構身份驗證與授權解決方案",
                    TopicOutline = "隨著企業應用邁向微服務化與雲原生架構，身份驗證與授權管理的重要性日益提升。透過 Keycloak 與 .NET 的整合，我們可以構建一個高效且符合企業級需求的身份驗證平台。本次演講將從設計到實現，探討開發者在身份驗證中面臨的挑戰，並分享 Keycloak 與 .NET 的整合實務及系統維運中的設計與優化策略。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "MikeHuang",
                    Name = "Mike Huang",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Mike.jpg",
                    BlogUrl = "https://wellwind.idv.tw/blog/",
                    FacebookUrl = "https://www.facebook.com/fullstackledder",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "台積電主任工程師、Angular GDE，主要熟悉 .NET WebAPI 與 Angular 開發技術，並經常於個人部落格分享學習知識。",
                    Topic = "Angular Signals 高效能開發演練",
                    TopicOutline = "Angular 近幾版大動作不斷，其中最引人注意的莫過於 Angular Signals 了，透過 Angular Signals 機制可以讓我們以更加 reactive 的方式開發彈性高且易於維護的程式，同時也帶來了更好的效能表現！<br/>本次分享將以 Angular Signals 為主軸，分享在實際專案開始導入 Angular Signals 後的經驗以及注意事項，幫助您快速開始使用 Angular Signals 開發高效乾淨的應用程式",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BillChung",
                    Name = "Bill Chung",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Bill Chung.jpg",
                    BlogUrl = "https://www.dotblogs.com.tw/billchung",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個單純喜歡說故事的人，擅長用簡單的語言解釋技術細節。",
                    Topic = "每年改一版，到底煩不煩",
                    TopicOutline = "C# 年年更新，這一次又帶來甚麼新語法？而這幾年如雪片般飛來的新語法，又有哪些是我特別推薦給大家認識。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JamesTsai",
                    Name = "James Tsai",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/James Tsai.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任 Microsoft MVP - Developer Technologies (2015~) 與 骨架資訊有限公司的技術總監。從 10 年多前開始接觸 .NET 程式開發後，經歷過撰寫各家行動平台的 App 與 Azure 雲端應用服務整合。Blog: https://xamarintech.blogspot.tw 與點部落: https://dotblogs.com.tw/jamestsai，內容涵蓋 Xamarin、Azure 服務與 Microsoft 365 的 Intune 相關應用等開發紀錄。並持續經營當前台灣最活耀的 Xamarin 社群 (Facebook 社群名稱: Xamarin Asia Developers)，與專注於跨平台應用開發與 CI/CD 整合、企業行動化資料保護…等的技術的研究與推廣。",
                    Topic = "在一種 A.I. 各桌表述，也精煉著所用的 A.I.?",
                    TopicOutline = "Avalonia UI 是一套 .NET 的跨平台 UI 開發技術，雖很少在過往主流 .NET 開發技術當中被提到，但此套跨平台 UI 開發技術在不少應用場景上的表現不亞於 .NET MAUI，尤以跨平台的\"桌面\"應用平台上的表現可說更勝 .NET MAUI 一籌。而如今在生成式 A.I. 技術所使用的相關 LLM 模型時，除了能透過 RAG 快速取得效果外，進一步透由\"適合\"的微調(Fine-tuning) 模型時，則更使其生成式 A.I. 的回應會有更佳的表現。但...當要進行微調(Fine-tuning) 模型時，有良好與符合期待的資料才能達到其效果，否則永遠就是 G.I.G.O.🚮🚮🚮<br/>讓適合的族群在一定合理的操作下，去衍生微調(Fine-tuning) 模型所需要的資料，又不需要過度的外部介入，並進行良好的資料採收，跨桌面應用的情境會則是比較合理的選擇，這將讓 Avalonia UI 成為一個可以活用其長處的選項。並且 Avalonia UI 本身的 Fluent Theme 也一部分完善的實踐了 Fluent Design System ，讓其 UI/UX 的體會不同以往打造桌面應用的感受。<br/>此議程將快速且重點的展示上述各項，激盪各位 ,NET 開發者可以有的發揮與想像。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Weithenn",
                    Name = "王偉任 Weithenn",
                    JobTitle = "Micron - IT Staff Architect",
                    PictureUrl ="./img/speakers/Weithenn.jpg",
                    BlogUrl = "https://www.weithenn.org/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續十三年成功獲選 Microsoft MVP 和 VMware vExpert 技術專家，並長期擔任網管人雜誌技術專欄作家。<br/>曾擔任 Kubernetes Summit 2024, Hello World Dev Conoference 2024, DevOpsDays Taipei 2024、Cloud Summit 2024、SRE Conference 2024、DevOpsDays Tokyo 2024、Google DevFest Taipei 2023、.Net Conf Taiwan 2023、Modern Web Conference 2023、Kubernetes Summit 2023、DevOpsDays Taipei 2023、COSCUP 2023、Cloud Summit Taiwan 2023……等研討會講師。<br/>專長為打造 SDDC 軟體定義資料中心、HCI 超融合解決方案、IaC 基礎架構即程式碼環境……等，著有微軟 S2D 軟體定義儲存技術實戰……等共 19 本著作。",
                    Topic = "LLM 初體驗 - Running Microsoft Phi-3 locally",
                    TopicOutline = "在本議程中，將說明和實際展示，如何快速將 Microsoft 推出的開放式大型語言模型 Phi-3，在本地端電腦上運作，即便沒有 GPU 資源的桌機或筆電 (有當然更好!)，也都可以運作 Phi-3 開放式大型語言模型，讓手邊沒有 GPU 資源又想體驗 LLM 大型語言模型威力的 IT 人員，都能輕鬆體驗 Phi-3 的威力。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JamesFu",
                    Name = "James Fu",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/James Fu.jpg",
                    BlogUrl = "https://dotblogs.com.tw/jamesfu",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一位資深的資料庫專家，擁有豐富的 SQL Server 管理經驗，專精於資料庫高可用性架構、效能調校以及雲端服務整合等領域。他經營的技術部落格「五餅二魚工作室」，分享了大量實務經驗與技術文章，涵蓋從 SQL 語法優化到 Azure 雲端服務應用等多元主題。",
                    Topic = "在 OpenAI 中加入一點創意讓 ESG 更為輕鬆",
                    TopicOutline = "透過 Live demo 簡介一些我們在 OpenAI 上的應用 , 透過 OpenAI 與圖像識別, 讓 IT 人員可以在 ESG 的領域有更多的發揮與應用",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "CaiWenlong",
                    Name = "蔡文龍",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/蔡文龍.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續16年微軟最有價值專家(AI + Developer 雙領域 MVP)、專業電腦圖書作家，著有超過130本以上電腦書籍，現任職於僑光科技大學多媒體與遊戲設計系副教授，專長雲端應用程式、人工智慧軟體服務、遊戲設計，同時受聘各公民營企業、內訓課程開發規劃。",
                    Topic = "「一聲相識」：使用Azure OpenAI聊天完成與語音服務建立具聽說功能的客服聊天機器人",
                    TopicOutline = "此次議程將引導學員深入學習如何運用 Azure OpenAI 的語音與聊天完成服務，打造具備聽說雙向互動功能的智能客服聊天機器人。課程內容涵蓋了 Azure OpenAI 平台上 GPT-4 進行聊天完成、TTS 文字轉語音、Whisper 語音辨識模型的部署與應用，並介紹如何使用 Python 或 C# 整合聊天和語音技術，以提升機器人的互動體驗。透過實作練習，學員將能夠設計出能夠透過語音即時回應客戶需求的客服機器人，實現更貼近人類自然對話的溝通體驗。",
                    Room ="202 教室",
                    Track ="Azure",
                    SessionStart = new DateTime(2020, 12, 19, 10, 0, 0),
                    SessionEnd = new DateTime(2020, 12, 19, 10, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM" },
                },
                new SpeakerModel {
                    Id = "OuZhixin",
                    Name = "歐志信",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/歐志信.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續16年微軟最有價值專家、資訊圖書作者，現任職於電信業，協助政府機關與企業客戶導入生成式AI、智慧影像辨識（人臉辨識、人形辨識）應用。",
                    Topic = "「一聲相識」：使用Azure OpenAI聊天完成與語音服務建立具聽說功能的客服聊天機器人",
                    TopicOutline = "此次議程將引導學員深入學習如何運用 Azure OpenAI 的語音與聊天完成服務，打造具備聽說雙向互動功能的智能客服聊天機器人。課程內容涵蓋了 Azure OpenAI 平台上 GPT-4 進行聊天完成、TTS 文字轉語音、Whisper 語音辨識模型的部署與應用，並介紹如何使用 Python 或 C# 整合聊天和語音技術，以提升機器人的互動體驗。透過實作練習，學員將能夠設計出能夠透過語音即時回應客戶需求的客服機器人，實現更貼近人類自然對話的溝通體驗。",
                    Room ="202 教室",
                    Track ="Azure",
                    SessionStart = new DateTime(2020, 12, 19, 13, 10, 0),
                    SessionEnd = new DateTime(2020, 12, 19, 14, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "hwchiu",
                //    Name = "邱宏瑋",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/hwchiu.png",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "目前擔任微軟 MVP (Cloud and Datacenter Management), Cloud Native Taiwan User Group 志工; 喜愛撰寫部落格分享技術，參加鐵人賽並出版 Kubernetes 相關書籍，亦有開設 Kubernetes 線上課程並經營個人 粉絲團 定期分享 Cloud Native 相關新知",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "RobersonLiou",
                //    Name = "Roberson Liou",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/RobersonLiou.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "現任微軟最有價值專家（Developer Technologies），也是 twMVC 及 DevOps Taiwan 的社群志工。<br/>喜歡參加社群的技術交流活動，並不定期在部落格（工程良田的小球場）上記錄自己踩坑的一些心得。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "LinZhengxiang",
                //    Name = "林正祥",
                //    JobTitle = "",
                //    PictureUrl ="./img/speakers/林正祥.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "樂於研究與分享新技術，喜歡使用各項網頁技術解決各項問題。主要專研 .NET 相關 Solution 為主，以及 Angular & Vue.js 等前端技術，並在第十二屆 iT 邦幫忙鐵人賽中的 Modern Web 組獲得佳作。於 2022 年出版 ASP.NET Core 6 實戰守則：超易懂的跨平台開發入門教學，並榮登天瓏年度排行第二名",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "EvanceKao",
                    Name = "Evance Kao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Evance Kao.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "從天氣預報斜槓到軟體開發，從每天看雲轉變為服務上雲，喜歡從不同角度看同一件事情、抽象化各種業務邏輯、製造小輪子以揣摩米其林輪胎的設計。大多鑽研 DevOps (專注在 CI/CD)、系統架構與雲端服務，實務上則有 6 年以上的雲端架構設計、開發及維護經驗，並具有公有雲助理級證照。<br/>現在專注於商品搜尋與推薦領域，嘗試以 AI 讓大家能更好的買買買。<br/>過去分享：<br/>* 更好的開發體驗 - 建造 SDK 接上 API 的腿 @ .NET Conf Taiwan 2022<br/>* 容器化你的 .NET 生產線 @ STUDY4 2023 小聚",
                    Topic = "逐步實現智慧商品搜尋系統：從關鍵字搜尋到向量資料庫與 AI 整合",
                    TopicOutline = "在這場演講中，我們一起探索如何打造一個智慧、精準的商品搜尋系統！從基礎建設到利用 AI 強化搜尋體驗，我將帶領大家一步步實現一套符合現代需求的搜尋解決方案。<br/>🚀 基礎建設：以 ASP.NET Core 與 Elasticsearch 基於 Azure 快速建立穩定的搜尋架構。<br/>🔍 精準搜尋：實作關鍵字搜尋與多層過濾，提升用戶搜尋體驗。<br/>🤖 AI 智慧化：結合向量資料庫與 Azure OpenAI，賦予搜尋系統理解語意的能力，實現語意搜尋與個性化推薦。<br/>不論您是搜尋系統的新手還是尋求創新解決方案的專家，這場演講將帶給您啟發與實作方向！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 0, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "JimmyLiao",
                //     Name = "Jimmy Liao",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/JimmyLiao.jpg",
                //     BlogUrl = "https://jimmyliao.net/",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "https://www.linkedin.com/in/jimmyliao/",
                //     Introduction = "Jimmy Liao 先後就職於 Appier/Microsoft/InfuseAI/IBM 。專業技能橫跨應用程式、手機應用、後端開發、廣告投放、機器學習專案開發，近期致力於 Generative AI 以及相關應用推廣，協助客戶技術落實及技術諮詢。目前為 Google 生成式 AI 開發專家 (Google Developer Expert of Generative AI)。<br/>日常生活就是跑步，曾經以跑步為通勤工具之一 (單程 20+ km)。接下來目標是台北馬拉松/大阪馬拉松",
                //     Topic = "GenAI 的下一個戰場：Azure AI Search 對決 Vertex AI Search",
                //     TopicOutline = "本次演講將深入剖析兩大服務的功能、優劣勢與應用場景，助您選擇最佳解決方案。<br/>- 生成式 AI 與企業搜尋的結合。並以一個完整案例，示範如何使用 Azure AI Service 作為開發與部署平台。<br/>- 核心功能與特色<br/>- 實際應用案例<br/>- 優缺點分析<br/>- 適用場景分析<br/>",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                //     SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "Chuck",
                    Name = "陳復楷",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Chuck.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "台積電資深工程師，穿梭於各大社群，熱情的南部鄉親",
                    Topic = "咱一路建置 Observability 的風風雨雨",
                    TopicOutline = "分享在大型企業SRE領域中的冒險故事，像是穿越迷霧、攀越高峰，甚至偶爾踩到坑洞的真實寫照。這場演講將分享如何從零開始，Observability 導入的實踐之路，包括面對的挑戰、成功的經驗。從指標、日誌到追蹤，從混亂到清晰，本演講將揭露如何將風風雨雨轉化為穩固的基石，助力系統穩定運行。",

                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "ChrisLiu",
                    Name = "Chris Liu",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Chris Liu.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "前某義大利餐廳行政主廚，曾於兩間台灣金流界龍頭任職，也曾擔任過某電子支付公司研發部主管，現為 Geek & Nerd Studios CEO 喜歡協助客戶完成技術導入，對他而言程式就跟料理一樣 keep learning, keep your knife sharpen。",
                    Topic = "在 Azure 上 building 與 scalling cloud-native 的智慧型app",
                    TopicOutline = "了解如何在 Azure 上透過 Azure Kubernetes Service 和 Azure Container Apps 運行cloud-native 的 serverless  和container 應用程式",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KeiLiao",
                    Name = "Kei Liao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KeiLiao.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "從 Android 及 iOS 轉往 C# .NET 後端的資深工程師，持續在工程師的道路上精進自己。",
                    Topic = "以程式碼撰寫符合 OpenAPI 規範的 Web API 文件：使用 TypeSpec",
                    TopicOutline = "開發者除了寫程式以外也常需要寫文件，透過適合的工具可以有效降低撰寫 API 規格文件的成本。本議程將介紹 TypeSpec，一個專為 API 開發設計的現代語言，讓開發者能夠以簡潔的語法快速定義並生成 Web API 規格文件，並示範如何將其融入在日常開發流程之中。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "WangQuanfu",
                    Name = "王泉富",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/王泉富.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個喜歡從零開始學習的工程師",
                    Topic = "全面掌握 Swagger 文件的「念」能力：讓你的 API 無懈可擊！",
                    TopicOutline = "在完成 API 開發後，你是否會注意過那些能讓 API 使用更清晰的小細節？身為開發者，我們該如何讓自己的 Swagger 文件更具質感、使用上更直觀呢？在這個議程裡，我們會來探討這個主題，一起了解如何讓 Swagger 文件清楚易懂，並具備實用性。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "ArthurChang",
                    Name = "Arthur Chang",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Arthur Chang.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "專注領域驅動設計與軟體架構，多年實戰經驗，涵蓋敏捷開發、微服務、架構演進等。擅長結合業務需求與技術實現，提供實用解決方案。",
                    Topic = "領域驅動設計下的持續架構",
                    TopicOutline = "領域驅動設計下的持續架構結合業務與技術，透過DDD實現模組化設計，以應對快速變化的需求，同時支持持續交付，架構演進與團隊協作，確保系統穩定性與可維護性。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JrtingShiau",
                    Name = "蕭晊莛",
                    JobTitle = "Technical Manager",
                    PictureUrl ="./img/speakers/Jrting Shiau.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前任職於新加坡商鈦坦科技，擔任 Technical Manager",
                    Topic = "API 協議選擇之道：REST、gRPC、GraphQL 如何匹配需求？",
                    TopicOutline = "本講題將以循序漸進的方式，深入解析 REST、gRPC、GraphQL 三大 API 協議的核心特性，探討它們的優缺點，並結合現代微服務架構的需求，分享如何在不同場景中選擇最適合的解決方案。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 14, 0, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 15, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                }
            };

            return speakers;
        }
    }
}
