using dotnetConf2024.Shared.Models;

namespace dotnetConf2024.Shared.Services
{
    public class SpeakerService
    {
        public IEnumerable<SpeakerModel> GetSpeakers()
        {
            var speakers = new List<SpeakerModel> {
                new SpeakerModel {
                    Id = "WillHuang",
                    Name = "Will Huang",
                    JobTitle = "多奇數位創意 技術總監",
                    PictureUrl ="./img/speakers/Will 保哥.jpg",
                    BlogUrl = "http://blog.miniasp.com/",
                    FacebookUrl = "https://www.facebook.com/will.fans/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任「多奇數位創意有限公司」技術總監。2018 年榮獲 Angular 方向的 Google Developer Expert (GDE) 開發專家。連續 16 度當選微軟最有價值專家(MVP)。2019 獲選微軟技術社群區域總監 (Microsoft Regional Director)。熟悉 Angular、JavaScript、.NET、C#、ASP.NET MVC、Go、Docker、Kubernetes 相關技術。擅長 DevOps 與組織文化建立、軟體團隊建構與管理。熱愛分享知識。",
                    Topic = "ASP.NET Core 8.0 全新功能探索",
                    TopicOutline = ".NET 8.0 的全新推出，不僅為我們帶來了一系列驚人的效能提升，還引入了豐富的新特性與功能。作為最新的 LTS（長期支援）版本，它提供了極致的穩定性與安全性，這對於企業來說，是一項關鍵的考量。因此，選擇升級到 .NET 8 將成為一個不可或缺的決策。<br/>此外，ASP.NET Core 8.0 攜手 Visual Studio 2022 的最新版和 C# 12 的語言創新，將為開發者帶來前所未有的激情和活力。<br/>在這場演講中，我將帶領大家一起乘風破浪，探索 ASP.NET Core 世界的最新領域，一同發現未知的可能！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 10, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 11, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "DavidTung",
                    Name = "David Tung",
                    JobTitle = "光岩資訊資深技術顧問",
                    PictureUrl ="./img/speakers/David Tung.jpg",
                    BlogUrl = "http://studyhost.blogspot.tw/",
                    FacebookUrl = "http://www.facebook.com/DotNetWalker/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "光岩資訊資深技術顧問、歷屆微軟 TechDays、TechED 研討會講師、連續 14 年榮獲微軟最有價值專家 (MVP)、LINE API Expert(LAE)，專長領域跨及.NET開發技術、Azure DevOps、AI、ChatBot...熟悉 BPM、APS、ERP…等企業應用資訊系統之建置與導入。David 是敏捷開發與 DevOps 的熱愛者，打從 Apple II 時代開始闖蕩江湖至今，在資訊業各領域均有參與。做過 MIS/IT、當過 RD、帶過專案、團隊、也賣過軟體，寫過（這年頭已經消失了的）雜誌專欄、長年擔任企業訓練講師與顧問，出過一堆書……打從沒有物件導向，沒什麼所謂軟體生命週期管理的年代，一路經歷了無數個壯觀的大小瀑布與千瘡百孔的雷與坑、一直到今天，依舊還是一個喜歡寫 Code 的人...",
                    Topic = "給你滿滿的 OpenAI API 範例集",
                    TopicOutline = "既然，未來已不可能離開 AI，那我們就徹底擁抱它吧。這個場次，我們來仔細看看， .NET 開發人員該何使用 OpenAI API，並且搭配 Azure、Azure DevOps 、Power Automate...實現各種應用。總之，這一場就是直接帶給你滿滿的 OpenAI API 範例集啦。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 16, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 17, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "EdwardKuo",
                    Name = "Edward Kuo",
                    JobTitle = "Microsoft Regional Director",
                    PictureUrl ="./img/speakers/Edward Kuo.jpg",
                    BlogUrl = "https://profile.edwardkuo.dev/",
                    FacebookUrl = "https://www.facebook.com/groups/286316594814216/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "用不同觀點看待軟體開發流程，具有超過十年以上開發者經驗與技術。熱愛技術也喜愛探索商業需求，在需求與技術槓桿中選擇合適的解決方案。專注於雲端架構設計與開發、供應鏈系統設計、ML/ AI、資訊安全和DevOps解決方案，擔任DevOps相關研討會、企業 DevOps 講師以及微軟技術研討會之講師",
                    Topic = "使用Azure邁向Platform Engineering之路",
                    TopicOutline = "平台工程是一門構建工具和工作流程的學科，這些工具和工作流程為軟體工程團隊提供自助服務功能。它可以改進開發人員的體驗，減少他們的認知負荷，並提高生產力。平台工程通過標準化工具和服務，簡化了開發和維運的流程，並且在2024年將獲得顯著的發展，我們如何整合地端與Azure技術邁向這條路",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 15, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 16, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "AndrewWu",
                    Name = "Andrew Wu",
                    JobTitle = "91APP 首席架構師",
                    PictureUrl ="./img/speakers/Andrew Wu-4.jpg",
                    BlogUrl = "https://columns.chicken-house.net/",
                    FacebookUrl = "https://www.facebook.com/andrew.blog.0928/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任職於大型軟體開發團隊的架構師，負責核心產品的服務化，與內部產品開發團隊的架構改善等任務。在過去的 20 年工作經驗，主要都專注於 Microsoft .NET Framework 開發 SaaS , B2B2C 的雲端服務。我專長的領域包括: 軟體工程，物件導向設計，分散式系統架構設計，平行處理，API 設計 及 微服務導向架構設計 (microservices) 等。<br /><br />我樂於分享技術新知與開發的經驗，常在各大研討會或是在社群活動上分享經驗。同時我也有撰寫部落格文章的習慣，希望能累積我的經驗給需要的夥伴們。我深信知識是越分享越精進的，這也是支持我自 2004 至今連續 20 年不間段分享文章的動力來源。<br /><br />個人經歷:<br />- 現任 91APP, 首席架構師 Chief Architect<br />- 榮獲 Microsoft MVP 微軟最有價值專家 獎項,2016 ~ 2025<br />- 擔任多次 Microsoft Azure Cafe, TechDays, TechEd, DevOpsDays Taiwan, .NET Conf 等大型研討會講者，與相關 Azure PaaS 雲端系列課程與企業內訓講師<br /><br />https://columns.chicken-house.net/about/",
                    Topic = ".NET RAG 神器 - Microsoft Kernel Memory 的應用",
                    TopicOutline = "1. RAG 基本觀念<br />2. Kernel Memory Service 介紹<br />3. Hello, Kernel Memory<br />4. 搭配 No Code Platform - DIFY 的進階應用",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 11, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BruceChen",
                    Name = "Bruce Chen",
                    JobTitle = "Kingston Senior Engineer",
                    PictureUrl ="./img/speakers/Bruce Chen.jpg",
                    BlogUrl = "https://blog.kkbruce.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "任職於全美前 50 大私人企業，連續 12 年榮獲微軟最有價值專家，負責大型 B2B 資料交換、Web API 架構、Docker、Kubernetes 等系統平台架構與設計。由 ASP.NET 2.0(WebForms) 進入 .NET 的世界，喜歡分享心得於 blog.kkbruce.net 部落格，瀏覽量超過七百萬。合著作品有《ASP.NET MVC4 網站開發美學》、《ASP.NET MVC 5網站開發美學》；合譯作品《Martin Fowler 的企業級軟體架構模式》。經常於社群與研討會分享 .NET 開發與容器平台經驗，對於 ASP.NET Web API 框架有深入研究，是台灣宣導 ASP.NET Web API 的先驅。",
                    Topic = "Visual Studio 2022 開發工具大補帖",
                    TopicOutline = "地表最強開發工具 Visual Studio 並不會因為它是最強就停止它成長。可惜的是，開發人員只專注在編輯器畫面裡敲打程式碼，並沒有發揮出 Visual Studio 所帶來的強大的功能。近期 Visual Studio 對於 Web API 開發工具進行多項的改善升級，讓 Web API 的開發人員有更為愉悅的的開發體驗。因此，本場次將深入淺出介紹 Visual Studio 為 Web API 新帶來 .http 功能，讓 .http 為您的 Web API 品質加分。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 10, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 11, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KevinYang",
                    Name = "Kevin Yang",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Kevin Yang.jpg",
                    BlogUrl = "https://blog.kevinyang.net/",
                    FacebookUrl = "https://www.facebook.com/CKNotepad/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前擔任 Angular Taiwan、Angular Girls Taiwan 、TypeScript Taiwan 社群管理者，Angular 線上讀書會主持人。2018 年榮獲 Angular/Web GDE (Google Developer Expert) 開發專家。微軟最有價值專家 (Visual Studio and Development Technologies)。熱衷分享任何新奇的技術資訊、不務正業(跨領域)，目前已跨入的領域有會計、醫療資訊及程式開發。",
                    Topic = "有在關注 AOT 嗎？ You Should",
                    TopicOutline = "有寫過 Go 的人應該知道 Golang compile 出來的檔案是不需要透過 language runtime 就可以執行，這樣的好處在 Cloud native 的世界裡真的很吃香，對比於其他 rumetime compile 的語言，例如 Java、.NET，Image size 隨便都 200 MB 起跳。 AOT 在 .NET 的世界裡不是第一次提出，但 .NET 8 是正式看待這件事情，就讓我們來看看 AOT 在 .NET 8 可以做到怎樣的程度。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 13, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 14, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JimmyHo",
                    Name = "Jimmy Ho",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Jimmy Ho-02.jpg",
                    BlogUrl = "https://jiaming0708.github.io/",
                    FacebookUrl = "https://www.facebook.com/secretgogoworld",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個熱愛學習、分享並且近期狂點前端技能樹的小小工程師，什麼都會什麼都不奇怪。",
                    Topic = "徹底搞懂 Blazor 的 Service Worker 機制",
                    TopicOutline = "在 Blazor WebAssembly 中開啟 PWA 的模式，讓服務可以離線工作載入，也可以接收從伺服器端發出的訊息，更可以在背景更新以上所說到的行為，到底是怎麼運作的，有沒有什麼要額外注意的地方，讓我們一次搞清楚。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 15, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 17, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "GelisWu",
                    Name = "Gelis 吳俊毅",
                    JobTitle = "資深 .NET 技術顧問 & Microsoft MVP 連續七屆",
                    PictureUrl ="./img/speakers/Gelis Wu.jpg",
                    BlogUrl = "http://gelis-dotnet.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/groups/361804473860062/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "我目前是個軟體生命週期導入專業顧問<br/>我專精於顧問與協助企業流程改造(電子化)協助將商業邏輯服務化、彈性化: 以 SOA 服務導向架構的方式提供 API 框架，讓各應用程式在開發時容易調用，加速開發、並可提高商業邏輯的再利用率，協助呈現介面多元化等。同時也擅長協助提升企業的軟體專案開發與工作效率，協助企業內部制定開發團隊流程 (Coding Rule/Standard) 與技術一致化，統一開發環境與技術、應用協同工作平台 Azure DevOps 建置雲端相關應用、自動化部署工具評估與導入。<br/>同時因為專案開發出身，我同時也擅長協助企業建置 ERP/CRM/CMS 或企業內部 EIP 等相關系統。",
                    Topic = "Blazor in .NET 8 的重大改變",
                    TopicOutline = "在 .NET 拓展到 8.0 後，為什麼 Blazor 卻又在底層架構上有這麼大的改變呢？所謂的 SSR 或 CSR 在我們原本的 Blazor 上要注意什麼呢？原先設計的元件 Blazor Components 是否有什麼要配合的地方？原先在 .NET 6/7 撰寫的 Blazor 應用程式如果要改成在 .NET 8 執行要做什麼改變呢？以及 Hosted by Server 也沒有了，有什麼新的方式可以取代呢？<br/>這這個場次，我們一次把它弄清楚。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 15, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 16, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BaoChengyou",
                    Name = "鮑承佑",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/鮑承佑.jpg",
                    BlogUrl = "https://linktr.ee/windperson",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "本人於 2007 年底投身資訊業，從原本寫 Java， 2009 年開始接觸 WPF、Silverligh t的 C# 桌面應用程式開始投入 .NET開發，之後於資拓宏宇擔任軟體專案工程師，於 2014 年投入遊戲業在台灣卡普空擔任開發組組長，2018 到2024 上半在XR領域相關新創擔任 CTO；Unity, Xamarin/MAUI, ASP.NET Core, Blazor, Azure SignalR 等前後端與Azure雲端開發技術都略懂略懂，但抓 bug 比較在行。",
                    Topic = "除了刻鋼板表單 CRUD 懂 C# 也能打造美幻 3D",
                    TopicOutline = "本議程介紹三個可用 C# 進行開發的 3D 遊戲/應用開發引擎：Unity、Godot 和 Stride Engine。Unity 是跨平台遊戲引擎，可輕鬆地創建 2D 和 3D 遊戲或應用。Godot 是臉書支持的 MIT 授權免費開源遊戲引擎，也支持使用 C# 進行程式撰寫。Stride Engine 是 MIT 授權開源 3D 跨平台遊戲引擎，使用 .NET 6 C# 開發，可讓開發者以 C# 10 的語言規格撰寫遊戲或商業應用。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 15, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 16, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "YinSangzhi",
                    Name = "尹相志",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/尹相志-AI.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "於 2002 年台灣創立 asiaMiner 為台灣第一家專業大數據顧問公司。2015 年正式擔任中國第一家大數據顧問公司華院數據的首席數據科學家，並於 2016 年發起中國首次人工智能大賽 BOT (Brain of things) 2016，目前於大陸成立 Deepbelief.ai 聚焦於機器視覺的創新商業應用。",
                    Topic = "榨出大型語言模型最大潛力的 Prompt 思考術",
                    TopicOutline = "ChatGPT 運用了思維鍊，大幅提升了面對到複雜的問題的解題能力，而後思維樹、思維圖乃至於 ReAct、自我批評等技巧更是擴展了大型語言模型的無限可能。在這個 Session 將會介紹思考術相關概念以及如何使用 Azure OpenAI Service 來實現。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 11, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "IanChan",
                    Name = "Ian Chan",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Ian.jpg",
                    BlogUrl = "https://medium.com/playtech",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/codeian/",
                    Introduction = "陳葵懋（Ian Chen），連續12年當選微軟最有價值專家(MVP/現為AI領域)，同時也是連續5年微軟認證講師（MCT）。<br/>目前任職於「一等一科技股份有限公司」，熟悉 .NET 開發、Azure 雲端，近年來專注於Azure Devops、K8s、OpenAI等技術<br/>，相信持續學習與分享能成長與收獲的更多，曾擔任微軟 TechDays、Devdays Asia 、Mopcon、Modern Web Conference等研討會講師。<br/>2024年策畫與共同著作第一本講述Azure OpenAI 的技術書籍：駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 （使用 .NET 與 Node.js）。。",
                    Topic = ".NET x AI，基於開源的「Semantic Kernel 」SDK 建構大型自然語言 (LLM) 生成式 AI 應用",
                    TopicOutline = "生成式 AI 應用的誘發劑是 Prompt，因此提示工程（Prompt Engineering）成為炙手可熱的議題，然而從開發層面來看，實作一個真實場景的生成式應用，<br/>除了 Prompt 之外往往會遇面臨到如何處理上下文記憶、Few-Shot、Embeddings、Plugins 等機制的整合，當然神人可以全面自已來實現，而凡人的你我不<br/>用現成解決方案就太對不起自已啦。<br/>Semantic Kernel 是 Microsoft 在打造 GitHub Copilot、M365 Copilot、Bing Chat 所用的核心，現已開源是一個輕量化的 SDK 且即將正式迎來 1.0 版本，<br/>它支援 C#、Python、Java、TypeScript 程式語言，將開發生成式 AI 應用以 Pipeline 概念展開，提供一個生成式 AI 應用開發 Pattern。<br/>本場次除了帶大家來認識 Semantic Kernel 之外，我也將示範如何使用 Semantic Kernel，融合 GPT 模型，透過 Prompt 及 Plugin，打造生成式 AI 應用。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 14, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 15, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KoKo",
                    Name = "KO KO",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KO KO.jpg",
                    BlogUrl = "",
                    FacebookUrl = "https://www.facebook.com/magic.panda.engineer/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Ko Ko 是一位資深的軟體工程師，也連續四年獲得微軟 AI 領域的最有價值專家（Microsoft AI MVP）獎項。他擔任許多技術年會的講者，包含了 COSCUP、ModernWeb、名古屋開源年會、香港開源年會、PyCon APAC、PyCon HK、DevDays Asia 等等的大型年會，累計已超過萬名聽眾。共同著作有《駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 (使用. NET 與 Node. Js)》一書，拿過天瓏書局暢銷排行榜第二名。經營臉書粉專「大魔術熊貓工程師」。Ko Ko 所撰寫系列文章「一起學習 Azure Machine Learning」是繁體中文圈關於 Azure Machine Learning 最完整的學習資源之一。",
                    Topic = "在 Azure Machine Learning 上學習 LangChain",
                    TopicOutline = "LangChain 是開發大語言模型應用最主流的框架之一，其簡單好上手的特性，讓開發者可以快速打造產品的原型。而 Azure Machine Learning 目前做 AI 研究與應用開發最主流的工具之一。其完整的功能以及和 Python 與 AI 相關的生態系整合相當完整。<br/>本次演講會為大家介紹 LangChain 的基本概念，包含 Model、Chain、Retriever 等重要元件，並且使用 Azure Machine Learning 上的功能做為範例。此外還會介紹如何把 LangChain 整合進到 Azure Machine Learning 裡面。讓開發者可以利用 Azure Machine Learning 的優勢，快速打大語言模型的應用程式。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 15, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 16, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JiaSin",
                    Name = "陳佳新（奇步老爹）",
                    JobTitle = "奇步應用有限公司 執行長",
                    PictureUrl ="./img/speakers/陳佳新.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "具備 LINE API Expert 及 Microsoft AI MVP 專家資格，推廣 Chatbot 聊天機器人及 AI 人工智慧技術落地不遺餘力，目前是中部人的聊天機器人小小聚、彰化 AMA 小聚、彰化 Google 技術開發者社團的活動主辦人，致力於提升故鄉彰化乃至中部地區的數位化能力，同時也是「彰化旅行+」的核心成員，來彰化吃喝玩樂歡迎指名！",
                    Topic = "用 AI Agent 分析萬人活動及校正異常",
                    TopicOutline = "在 LLM 大語言模型的時代，打造各種專屬功能的 AI Agent 成了開發者的日常，因應各行各業都遭遇的缺工問題， AI Agent 已經開始扮演起重要的智囊團角色，舉凡分析數據、提供建議，都可以借重 AI Agent 之力，所花費的時間甚至更少，所獲得成效甚至更棒。本議程將以我們在彰化舉辦的萬人參加的活動為例，說明 AI Agent 如何協助分析，提供決策參考，並且盡可能降低民眾人為因素所導致的異常，大幅提升活動的公平性。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 16, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 17, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "RyanChung",
                    Name = "Ryan Chung",
                    JobTitle = "Microsoft MVP",
                    PictureUrl ="./img/speakers/Ryan Chung.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Ryan Chung，行動開發學院創辦人，曾獲微軟人工智能大賽特別獎、Udacity AI 產品經理微學位。目前為美國 Pluralsight 認證講師、中央大學 AI 學程兼任講師、元智大學資工系兼任助理教授級專業技術人員。專長於 Web/App 應用開發、企業 AI 加值導入、微軟 OpenAI 與認知服務應用整合。2022 年起，獲選為微軟 MVP - AI 人工智慧最有價值專家。共同著作：駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐（使用 .NET 與 Node.js）。",
                    Topic = "有沒有一種可能，你需要的只是Azure AI 而不是 OpenAI",
                    TopicOutline = "隨著大型語言模型的功能日新月異，在令人讚嘆的驚呼聲中，其實裡面藏了許多\"並非\"一定要大型語言模型不可的功能。本場次想要與你一起談談那些 Azure AI 底下的好用服務。說不定，你需要的只是Azure AI。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 14, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 15, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Summit",
                    Name = "孫玉峰",
                    JobTitle = "台灣角川 數據架構師",
                    PictureUrl ="./img/speakers/孫玉峰.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "在多個產業開發各種資料產品，包含推薦系統以及廣告數據平台，近年來的公開演講以及實務上則專注在資料工程與 MLOps 的建立，期望讓數據驅動（Data-Driven）的觀念帶動各個產業領域的創新。<br/>在東吳及師大擔任業界講師，亦接受過各媒體專訪，目前也是微軟 AI 領域最有價值專家（MVP）以及 Taiwan R User Group（常態活動 MLDM Monday 主辦單位）的共同主持人。",
                    Topic = "連 MLOps 都沒聽過的我就要用 LLMOps 是不是搞錯了什麼？",
                    TopicOutline = "當他們在講 DevOps 的時候，我保持沉默，我又不是 SRE<br/>當他們在講 MLOps 的時候，我保持沉默，我又不是 Data Engineer<br/>當他們在講 LLMOps 的時候，已經沒有人能為我說話了<br/><br/>去年（2022）以來大型語言模型（LLMs）的發展正在大幅改變產品開發的樣貌，不論是用 Copilot 協助程式開發、或是直接將 ChatGPT API 包進產品裡，都讓 AI 的應用及產品開發出現更多可能性；原本大概只在特定領域會出現的 ML 開發，現在也跟著 LLMs 變成萬物皆可 AI。<br/>隨著 LLMs 漸漸成為開發人員基本標配，相關的部署及維運問題也隨之而來，LLMOps（Large Language Model Operations）就成了無法逃避的議題。<br/>這場分享將會從一個簡單的推薦系統案例開始，透過逐步完善產品的過程中，去理解 LLMOps 的精髓。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 15, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 14, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BenChen",
                    Name = "陳奎銘",
                    JobTitle = "Principal Data Scientist @ OneLab",
                    PictureUrl ="./img/speakers/BenChen.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "有幸成為微軟 AI 領域 MVP 的資料科學家，致力於用資料科學解決各個領域的疑難雜症，舉凡投資、生技醫療和其他傳統產業，都有相關實務處理的經驗。除此之外，不定期也會接到授課的邀約，協助不同組織機構初探數位轉型，進入資料科學的世界。同時，我也是 R-Ladies Taipei Co-organizer，正嘗試努力每個月都舉辦活動，繼續延續社群的活力。",
                    Topic = "投資？我都交給我的高級伴讀書僮 - GPT！",
                    TopicOutline = "生成式 AI 從年初燒到了年尾，大家的生活可能都受到一定程度的衝擊與恩惠，各種應用也是隨之產生。但是，不是少了些什麼？<br/>在夜深人靜的時候，獨自看著美股起起伏伏，是不是心中的悸動也油然而生？有點想要跟著這波行情衝一波，但感覺又有點怕怕的…<br/>只好，打造自己的高級伴讀書僮了！讓 GPT 陪你搞懂每家公司，指引出股海中的偉大航道！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 13, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 14, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "AlanTsai",
                    Name = "Alan Tsai",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Alan Tsai.jpg",
                    BlogUrl = "https://blog.alantsai.net/",
                    FacebookUrl = "http://fb.alantsai.net/",
                    TwitterUrl = "http://twitter.alantsai.net/",
                    LinkedinUrl = "http://linkedin.alantsai.net/",
                    YouTubeUrl = "http://yt.alantsai.net/",
                    Introduction = "深耕 .NET 軟體開發多年，深信使用的技術不是重點，重點在於如何全面的思考並且用適合的技術解決客戶的問題，為現任的微軟最有價值專家（Microsoft MVP）- Azure，微軟認證講師（MCT），樂於分享，深信教就是最好的學習方式，定期發佈部落格（Alan Tsai 的學習筆記）文章、影片、演講分享或者幫忙翻譯。很宅，除了上班之外會出去應該都是參加/協助社群活動（Azure Taiwan），為現任 Study4.TW 成員之一。除了程式以外，就愛看小說。",
                    Topic = "探索 API 開發的挑戰與解決之道",
                    TopicOutline = "相信大家對於為什麼要把服務 API 化的原因都清楚了，但是該怎麼開始呢？如果要走 API Design First 那怎麼可以產生出好持續維護的 OpenAPI (Swagger) 文件作為溝通的 Contract 呢？API 開發完上線之後怎麼能夠確保安全，以及出錯如何追蹤問題呢？如果只是單純的 DB 異動的 CRUD 需要建立後端 API 嗎？隨著 API 數量變多怎麼收攏所有有提供的 API 呢？<br/>在這場，我們來看一下針對一些 API First 遇到的問題，微軟提供了那些解決方案給我們。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 13, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 14, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "AlanTsai",
                    Name = "Alan Tsai",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Alan Tsai.jpg",
                    BlogUrl = "https://blog.alantsai.net/",
                    FacebookUrl = "http://fb.alantsai.net/",
                    TwitterUrl = "http://twitter.alantsai.net/",
                    LinkedinUrl = "http://linkedin.alantsai.net/",
                    YouTubeUrl = "http://yt.alantsai.net/",
                    Introduction = "深耕 .NET 軟體開發多年，深信使用的技術不是重點，重點在於如何全面的思考並且用適合的技術解決客戶的問題，為現任的微軟最有價值專家（Microsoft MVP）- Azure，微軟認證講師（MCT），樂於分享，深信教就是最好的學習方式，定期發佈部落格（Alan Tsai 的學習筆記）文章、影片、演講分享或者幫忙翻譯。很宅，除了上班之外會出去應該都是參加/協助社群活動（Azure Taiwan），為現任 Study4.TW 成員之一。除了程式以外，就愛看小說。",
                    Topic = "從 GitHub Copilot 到 Enterprise Copilot：打造符合企業需求的智能開發助手之路",
                    TopicOutline = "隨著 ChatGPT 的崛起，Generative AI 已經變得非常普遍。GitHub Copilot 是針對工程師在這一浪潮誕生的強大工具。<br/>如果你曾使用過 GitHub Copilot，你一定會對它的「讀心」功能感到驚奇。然而，它並不總能完美地滿足我們的需求。但只要我們理解它的運作原理，我們可以透過不同的方式，使其產生符合我們需求的程式碼。<br/>然而，要讓整個企業充分受益，不僅需要了解Copilot的運作方式，還需要確保生成的程式碼符合特定的企業規範和風格。這正是為什麼 Copilot Stack 這一整套解決方案應運而生，它使我們能夠開發出符合企業需求的 Copilot。<br/>在本次分享中，我們將探討GitHub Copilot 的重要性，並深入研究如何開始打造符合企業需求的 Copilot。我們將了解如何結合Semantic Kernel、Azure Prompt Flow和Visual Studio Code，以建立一個符合內部規範的 Copilot，並推動智能開發助手的進一步應用和發展。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 10, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 11, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "MarcusTung",
                    Name = "Marcus Tung",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Marcus Tung.jpg",
                    BlogUrl = "https://marcus116.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/marcus.tung.3",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家（Developer Technologies）和 DevOps Taiwan 技術社群志工，樂於研究與分享 後端技術，將學習與實踐的心得記錄在個人部落格 m@rcus 學習筆記上，並於粉絲團不定期分享技術開發與 Observability 相關新知。",
                    Topic = ".NET 8 x OpenTelemetry ",
                    TopicOutline = "OpenTelemetry 是雲原生基金會(CNCF)推出 Kubernetes 之外的最熱門的開源專案之一，它整合 OpenTracing 和 OpenCensus 成為從應用程式收集遙測數據的新標準。此議程將探討 .NET 8 如何擁抱 OpenTelemetry，實現了日誌和指標的全面擴展，並且如何遵循 OpenTelemetry Semantic Conventions 來優化應用程式的遙測實踐。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 16, 30, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 17, 20, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Mike",
                    Name = "黃升煌 Mike",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Mike.jpg",
                    BlogUrl = "https://wellwind.idv.tw/blog/",
                    FacebookUrl = "https://www.facebook.com/fullstackledder",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前是 Microsoft MVP 及 Angular，熟悉 .NET WebAPI 與 Angular 開發技術，主要於個人部落格分享學習知識，並活躍於 Angular Taiwan Facebook 社團。",
                    Topic = "無密碼時代降臨！使用 Passkeys 打造無密碼驗證服務",
                    TopicOutline = "在這個數位時代，資安事件層出不窮，密碼外流事件頻傳，傳統的密碼登入方式已經不再安全，或只能用更複雜的密碼，想辦法降低攻破難度，我們迫切需要一種更安全的解決方案。<br/>幸運的是，現在我們有了一個令人振奮的解決方案 - Passkeys！FIDO 聯盟推出的 Passkeys 規格，將完全改變我們登入的方式。現在，使用者不再需要記住繁瑣的密碼，只需擁有自己的 Passkey，就能輕鬆完成驗證。同時，這也意味著網站管理者不再需要儲存使用者的密碼，消除密碼外洩以及釣魚網站帶來的風險。<br/>本次分享將帶您深入探索 Passkeys 的原理，並透過實際的程式碼示範，展示如何實現 Passkeys 驗證服務。讓我們一同踏入安全的無密碼時代，探索未來資安的新里程碑！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 11, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BillChung",
                    Name = "Bill Chung",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Bill Chung.jpg",
                    BlogUrl = "https://www.dotblogs.com.tw/billchung",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個單純喜歡說故事的人。",
                    Topic = "歷史上的今天，變化多端的 C#",
                    TopicOutline = "近年來 C# 演變神速，出現了許多新式的語法，這個議程裡不僅談論今年的 C# 12，也將挑選過去一些重要的語法變革。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 13, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 14, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JamesTsai",
                    Name = "James Tsai",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/James Tsai.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任 Microsoft MVP - Developer Technologies (2015~) 與 骨架資訊有限公司的技術總監。從 10 年多前開始接觸 .NET 程式開發後，經歷過撰寫各家行動平台的 App 與 Azure 雲端應用服務整合。Blog: https://xamarintech.blogspot.tw 與點部落: https://dotblogs.com.tw/jamestsai，內容涵蓋 Xamarin、Azure 服務與 Microsoft 365 的 Intune 相關應用等開發紀錄。並持續經營當前台灣最活耀的 Xamarin 社群 (Facebook 社群名稱: Xamarin Asia Developers)，與專注於跨平台應用開發與 CI/CD 整合、企業行動化資料保護…等的技術的研究與推廣。",
                    Topic = "從 Xamarin 到 .NET MAUI的全平台領域展開",
                    TopicOutline = "在Xamarin 帶給 .NET 開發人員跨平台開發行動應用的體驗後，微軟進一步的推出 .NET MAUI 技術，更在 .NET 8 中讓 .NET 開發人員能穩步地的透過 .NET MAUI 進行 Mobile 應用、桌面應用的全平台領域開發。<br/>本議程將介紹 .NET 8 帶來 .NET MAUI 的新優勢，並對比 Xamarin 與 .NET MAUI 間的設計差異。讓曾運用 Xamarin技術開發的 App去了解如何遷移到 .NET MAUI技術上，透過 .NET MAUI 更進一步的在各平台與裝置上，盡情揮灑創意與能力，開發出絕佳的前端原生應用程式。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 14, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 15, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Phi",
                    Name = "黃秉鈞",
                    JobTitle = "CNCF Ambassador",
                    PictureUrl ="./img/speakers/Phi.jpg",
                    BlogUrl = "https://blog.pichuang.com.tw",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "擔任 Microsoft Taiwan 的 Azure 資深雲端解決方案架構師，並同時為現任 CNCF Ambassador。他曾在 Red Hat 和 VMware 擔任資深售前架構師，擁有超過 7 年的企業級 IT 基礎架構設計經驗。因長期受到開源文化的薰陶，他在 Linux、Kubernetes 和混合雲網絡架構方面具有深厚的技術造詣和見識。作為一個開源愛好者，他積極將自己的知識透過文章撰寫和參與 Cloud Native Taiwan User Group (https://www.facebook.com/groups/cloudnative.tw) 社群的方式分享給他人。他深信透過開源技術和社群力量，可以幫助更多企業和使用者實現他們的目標。",
                    Topic = "Azure Kubernetes Services 永續性軟體工程設計方針",
                    TopicOutline = "今年 KubeCon NA 2024 的主題演講之一是探討雲端原生環境永續性 (Environmental Sustainability) 的原則和實踐，其中提到了希望大家在使用雲端原生的技術的時候，也能夠關注計算資源利用率和延伸的環境影響，設計出更加符合當前環境永續性的架構。本演講將會基於 Azure Kubernetes Services 來簡介採用現今 Green Software Foudantion 所提出的原則之下，如何設計出更加符合環境永續性的架構。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 13, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 14, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Weithenn",
                    Name = "王偉任",
                    JobTitle = "Micron - IT Staff Architect",
                    PictureUrl ="./img/speakers/Weithenn.jpg",
                    BlogUrl = "https://www.weithenn.org/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續十三年成功獲選 Microsoft MVP 和 VMware vExpert 技術專家，並長期擔任網管人雜誌技術專欄作家。<br />曾擔任 Kubernetes Summit 2024, Hello World Dev Conoference 2024, DevOpsDays Taipei 2024、Cloud Summit 2024、SRE Conference 2024、DevOpsDays Tokyo 2024、Google DevFest Taipei 2023、.Net Conf Taiwan 2023、Modern Web Conference 2023、Kubernetes Summit 2023、DevOpsDays Taipei 2023、COSCUP 2023、Cloud Summit Taiwan 2023……等研討會講師。<br />專長為打造 SDDC 軟體定義資料中心、HCI 超融合解決方案、IaC 基礎架構即程式碼環境……等，著有微軟 S2D 軟體定義儲存技術實戰……等共 19 本著作。",
                    Topic = "LLM 初體驗 - Running Microsoft Phi-3 locally",
                    TopicOutline = "在本議程中，將說明和實際展示，如何快速將 Microsoft 推出的開放式大型語言模型 Phi-3，在本地端電腦上運作，即便沒有 GPU 資源的桌機或筆電 (有當然更好!)，也都可以運作 Phi-3 開放式大型語言模型，讓手邊沒有 GPU 資源又想體驗 LLM 大型語言模型威力的 IT 人員，都能輕鬆體驗 Phi-3 的威力。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 14, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 15, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "hwchiu",
                    Name = "邱宏瑋",
                    JobTitle = "Microsoft MVP",
                    PictureUrl ="./img/speakers/hwchiu.png",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前擔任微軟 MVP (Cloud and Datacenter Management), Cloud Native Taiwan User Group 志工; 喜愛撰寫部落格分享技術，參加鐵人賽並出版 Kubernetes 相關書籍，亦有開設 Kubernetes 線上課程並經營個人 粉絲團 定期分享 Cloud Native 相關新知",
                    Topic = "不懂 CNI 別說你在玩 AKS",
                    TopicOutline = "CNI 作為 Kubernetes 內網路功能非常重要的一環，而 AKS 則根據自己網路環境打造一個專屬於自己環境的 Azure CNI。<br/>本次議程會討論 AKS Azure CNI 與其他常見 CNI 相比對 Kubernetes 管理人員所帶來的差異，並且探討 Azure CNI 的實作方式。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 14, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 15, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "RobersonLiou",
                    Name = "Roberson Liou",
                    JobTitle = "Microsoft MVP",
                    PictureUrl ="./img/speakers/RobersonLiou.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家（Developer Technologies），也是 twMVC 及 DevOps Taiwan 的社群志工。<br/>喜歡參加社群的技術交流活動，並不定期在部落格（工程良田的小球場）上記錄自己踩坑的一些心得。",
                    Topic = "Deploy Azure Function with KEDA on AKS",
                    TopicOutline = "本次議程將分享如何將 Azure Function 以容器化的方式運行在 AKS 之上，以及在跨團隊的協作下，該如何將其整合至 Pipeline 之中運行。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 11, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "LenLi",
                    Name = "Len Li",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Len Li.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "在製造業打滾的工程師，曾任職於台積電、頎邦。熱愛資訊技術的他，曾獲台積電金質營業秘密獎、頎邦資訊類資訊專家獎。目前任職於 Kingston IT，負責 B2B、MRP、Industry 4.0 等 Web 與 VSTO 應用程式開發。熟悉前端後端開發如 Angular 、Vue、React 以 Web API 以及 VSTO。",
                    Topic = "如何打造 User 心目中的 Excel - VSTO 開發經驗分享",
                    TopicOutline = "Microsoft Office 是每個人必備辦公軟體，然而身為開發人員的你是否曾經被 User 的 Excel 需求困擾著？是否常常收到來自 User 的抱怨？抱怨他們的日常工作不夠便利、不夠即時性、不夠自動化。<br/>如果你有遇到上述問題，不妨考慮一下 Visual Studio Tools for Office (VSTO)，它是一套 Microsoft Office 的開發框架，能用來開發和擴充你的 Excel、Word、PowerPoint 等 Microsoft Office 應用程式功能。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 10, 10, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 10, 11, 11, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "LinZhengxiang",
                    Name = "林正祥",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/林正祥.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "樂於研究與分享新技術，喜歡使用各項網頁技術解決各項問題。主要專研 .NET 相關 Solution 為主，以及 Angular & Vue.js 等前端技術，並在第十二屆 iT 邦幫忙鐵人賽中的 Modern Web 組獲得佳作。於 2022 年出版 ASP.NET Core 6 實戰守則：超易懂的跨平台開發入門教學，並榮登天瓏年度排行第二名",
                    Topic = "Entity Framework Core 8：創新與優化",
                    TopicOutline = "EF Core 8 推出了許多新的功能，包含了增強對 JSON 的支援、List.Contains、變更追蹤及延遲載入的增強….等，並提升效能。本次議程將快速帶大家了解這次更新帶來了哪些優化與新功能",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 11, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JimmyLiao",
                    Name = "Jimmy Liao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/JimmyLiao.jpg",
                    BlogUrl = "https://jimmyliao.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/jimmyliao/",
                    Introduction = @"Jimmy Liao 先後就職於 Appier/Microsoft/InfuseAI/IBM 。專業技能橫跨應用程式、手機應用、後端開發、廣告投放、機器學習專案開發，近期致力於 Generative AI 以及相關應用推廣，協助客戶技術落實及技術諮詢。目前為 Google 生成式 AI 開發專家 (Google Developer Expert of Generative AI)。<br />日常生活就是跑步，曾經以跑步為通勤工具之一 (單程 20+ km)。接下來目標是台北馬拉松/大阪馬拉松",
                    Topic = "GenAI 的下一個戰場: Azure AI Search 對決 Vertex AI Search",
                    TopicOutline = @"本次演講將深入剖析兩大服務的功能、優劣勢與應用場景，助您選擇最佳解決方案。<br />- 生成式 AI 與企業搜尋的結合<br />- 核心功能與特色<br />- 實際應用案例<br />- 優缺點分析<br />- 適用場景分析",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 10, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 11, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Dann",
                    Name = "吳典璋",
                    JobTitle = "Build School 軟體工程師培訓學校創辦人",
                    PictureUrl ="./img/speakers/Dann.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Build School 是最酷的軟體工程與IT專業培訓學校，也協助企業更有效的找到專業軟體人才! Dann 哥曾任職於微軟 Microsoft 開發工具 .NET / Visual Studio / Team Foundation Server (現名 Azure DevOps) 產品行銷經理，是一位熱情及樂於分享的軟體資訊愛好者，在資訊軟體技術持續演進的浪潮下，感受著 ChatGPT 及 AI Copilot 帶來的生產力，至今仍在 Azure、Power BI/Power Platform 領域持續學習前進，期望本次活動能與來賓及技術愛好者多聊聊，或有軟體工程師徵才需求也歡迎前來交流。",
                    Topic = "Microsoft 認證的學習路徑及高效考證心法",
                    TopicOutline = "這場來點輕鬆的話題及福利放送～取得證照對個人職涯成長的好處？對每天的技術日常工作幫助是什麼？我們將從資訊技術人員職涯成長的角度出發，及企業主管在招募用人時對認證的心態，分享 Microsoft 微軟認證的面面觀。從軟體開發者、系統管理者、資料管理及分析師、資安工程師等不同職能，在新一代的技術主軸上 - AI、Azure、Data Platform、Security 的認證職涯成長地圖。<br/>也將聊聊如何有效率地取得認證之學習心法，讓你少走彎路，從 Azure AZ900 基礎認證、到進階的 AZ104 系統管理 / AZ204 開發技術、AZ400 DevOps 等認證。<br/>最後分享認證大禮包，從學習材料與課程、練習題及考試優惠，一次放送！<br/>也將邀請微軟 MVP - Poy Chang，一同與大家聊聊在取得認證路上的心路歷程，是如何從 Azure AZ900 基礎認證，一路過關斬將拿到 AZ400 DevOps 認證。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 13, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 14, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "YvonneShih",
                    Name = "Yvonne Shih",
                    JobTitle = "台灣微軟 雲端解決方案架構師",
                    PictureUrl ="./img/speakers/Yvonne Shih.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Yvonne Shih 專注於 Azure 上的 Data & AI 技術，並基於 Azure 上的服務和合作夥伴協作開發更多解決方案。",
                    Topic = "Azure AI Studio 助 LLMOps 一臂之力",
                    TopicOutline = "LLM 是一類新的自然語言處理（NLP）模型，它們可以執行各種任務，如開放式問答、摘要等。LLMOps 是管理、部署和優化大型語言模型（LLM）的領域。而 Prompt Flow 是 Azure AI Studio 中讓開發者可以使用流程（flow）來連接 LLM、提示（prompt）、程式碼和其他工具，並快速、簡便和高效地進行 LLMOps。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 11, 0, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "PaytonChou",
                    Name = "Payton Chou ",
                    JobTitle = "台灣微軟 微軟技術中心 技術架構師",
                    PictureUrl ="./img/speakers/Payton Chou.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前擔任 Microsoft 台灣微軟技術中心技術架構師，負責雲端安全軟體開發流程與敏捷式專案管理，同時也提供雲端架構設計與各種雲端解決方案，憑藉多年的實務經驗，在雲端服務架構及商務應用發展方面，已幫助許多企業實現數位轉型。",
                    Topic = "DevSecOps 最佳實踐與 GitHub Advanced Security on Azure DevOps",
                    TopicOutline = "此議程將探討 DevSecOps 的最佳實踐，我們將介紹在軟體開發流程中整合安全性的關鍵概念，並提供實際案例和建議，以幫助參與者改善他們的軟體開發流程。同時，我們將深入研究 GitHub Advanced Security 在 Azure DevOps 中的應用，認識 Code scanning、Secret scanning、Dependency review 如何幫助我們進一步提升安全性。透過此議程將為開發人員提供實用的介紹，以建立更安全、更高效的開發流程。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 10, 10, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 11, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                
                new SpeakerModel {
                    Id = "EdwardCheng",
                    Name = "Edward Cheng",
                    JobTitle = "Technical Specialist - Intelligence",
                    PictureUrl ="./img/speakers/Edward Cheng.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "專責 Business Intelligence，包含資料分析與與商業應用之顧問諮詢服務。",
                    Topic = "Microsoft Fabric-人工智慧時代的資料平台解決方案",
                    TopicOutline = "Microsoft Fabric 是企業的所有分析解決方案，涵蓋資料移動到資料科學、Real-Time 分析和商業智慧等所有專案。 它提供完整的服務套件，包括 Data Lake、資料工程和資料整合，全都在一個地方。<br/>使用 Fabric 時，不需要再整合各種廠商的服務。 相反地，可以享受高度整合、端對端且便於使用的產品，其設計目的是要簡化使用者的需求。<br/>此平臺是以軟體即服務 (SaaS) 為基礎，其採用簡單且整合至全新的層級。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2024, 12, 9, 14, 20, 0),
                    SessionEnd = new DateTime(2024, 12, 9, 15, 10, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
            };

            return speakers;
        }
    }
}
